/** @license


 SoundManager 2: JavaScript Sound for the Web
 ----------------------------------------------
 http://schillmania.com/projects/soundmanager2/

 Copyright (c) 2007, Scott Schiller. All rights reserved.
 Code provided under the BSD License:
 http://schillmania.com/projects/soundmanager2/license.txt

 V2.97a.20121104+DEV
*/
(function(G,g){function $($,pa){function aa(a){return c.preferFlash&&u&&!c.ignoreFlash&&c.flash[a]!==g&&c.flash[a]}function r(a){return function(d){var e=this._s;!e||!e._a?(e&&e.id?c._wD(l+"ignoring "+d.type+": "+e.id):c._wD(l+"ignoring "+d.type),d=null):d=a.call(this,d);return d}}this.setupOptions={url:$||null,flashVersion:8,debugMode:!0,debugFlash:!1,useConsole:!0,consoleOnly:!0,waitForWindowLoad:!1,bgColor:"#ffffff",useHighPerformance:!1,flashPollingInterval:null,html5PollingInterval:null,flashLoadTimeout:1E3,
wmode:null,allowScriptAccess:"always",useFlashBlock:!1,useHTML5Audio:!0,html5Test:/^(probably|maybe)$/i,preferFlash:!0,noSWFCache:!1};this.defaultOptions={autoLoad:!1,autoPlay:!1,from:null,loops:1,onid3:null,onload:null,whileloading:null,onplay:null,onpause:null,onresume:null,whileplaying:null,onposition:null,onstop:null,onfailure:null,onfinish:null,multiShot:!0,multiShotEvents:!1,position:null,pan:0,stream:!0,to:null,type:null,usePolicyFile:!1,volume:100};this.flash9Options={isMovieStar:null,usePeakData:!1,
useWaveformData:!1,useEQData:!1,onbufferchange:null,ondataerror:null};this.movieStarOptions={bufferTime:3,serverURL:null,onconnect:null,duration:null};this.audioFormats={mp3:{type:['audio/mpeg; codecs="mp3"',"audio/mpeg","audio/mp3","audio/MPA","audio/mpa-robust"],required:!0},mp4:{related:["aac","m4a","m4b"],type:['audio/mp4; codecs="mp4a.40.2"',"audio/aac","audio/x-m4a","audio/MP4A-LATM","audio/mpeg4-generic"],required:!1},ogg:{type:["audio/ogg; codecs=vorbis"],required:!1},wav:{type:['audio/wav; codecs="1"',
"audio/wav","audio/wave","audio/x-wav"],required:!1}};this.movieID="sm2-container";this.id=pa||"sm2movie";this.debugID="soundmanager-debug";this.debugURLParam=/([#?&])debug=1/i;this.versionNumber="V2.97a.20121104+DEV";this.altURL=this.movieURL=this.version=null;this.enabled=this.swfLoaded=!1;this.oMC=null;this.sounds={};this.soundIDs=[];this.didFlashBlock=this.muted=!1;this.filePattern=null;this.filePatterns={flash8:/\.mp3(\?.*)?$/i,flash9:/\.mp3(\?.*)?$/i};this.features={buffering:!1,peakData:!1,
waveformData:!1,eqData:!1,movieStar:!1};this.sandbox={type:null,types:{remote:"remote (domain-based) rules",localWithFile:"local with file access (no internet access)",localWithNetwork:"local with network (internet access only, no local access)",localTrusted:"local, trusted (local+internet access)"},description:null,noRemote:null,noLocal:null};this.html5={usingFlash:null};this.flash={};this.ignoreFlash=this.html5Only=!1;var La,c=this,Ma=null,h=null,l="HTML5::",A,v=navigator.userAgent,i=G,R=i.location.href.toString(),
j=document,qa,Na,ra,k,D=[],sa=!0,y,S=!1,T=!1,p=!1,w=!1,ba=!1,n,kb=0,U,x,ta,I,ua,J,K,L,Oa,va,ca,da,ea,M,wa,V,fa,ga,N,Pa,xa,lb=["log","info","warn","error"],Qa,ha,Ra,W=null,ya=null,q,za,O,Sa,ia,ja,P,t,X=!1,Aa=!1,Ta,Ua,Va,ka=0,Y=null,la,B=null,Wa,ma,Z,E,Ba,Ca,Xa,s,Ya=Array.prototype.slice,H=!1,Za,u,Da,$a,C,ab,Ea=v.match(/(ipad|iphone|ipod)/i),F=v.match(/msie/i),mb=v.match(/webkit/i),Fa=v.match(/safari/i)&&!v.match(/chrome/i),Ga=v.match(/opera/i),Ha=v.match(/(mobile|pre\/|xoom)/i)||Ea,Ia=!R.match(/usehtml5audio/i)&&
!R.match(/sm2\-ignorebadua/i)&&Fa&&!v.match(/silk/i)&&v.match(/OS X 10_6_([3-7])/i),bb=G.console!==g&&console.log!==g,Ja=j.hasFocus!==g?j.hasFocus():null,na=Fa&&(j.hasFocus===g||!j.hasFocus()),cb=!na,db=/(mp3|mp4|mpa|m4a|m4b)/i,Q=j.location?j.location.protocol.match(/http/i):null,eb=!Q?"http://":"",fb=/^\s*audio\/(?:x-)?(?:mpeg4|aac|flv|mov|mp4||m4v|m4a|m4b|mp4v|3gp|3g2)\s*(?:$|;)/i,gb="mpeg4 aac flv mov mp4 m4v f4v m4a m4b mp4v 3gp 3g2".split(" "),nb=RegExp("\\.("+gb.join("|")+")(\\?.*)?$","i");
this.mimePattern=/^\s*audio\/(?:x-)?(?:mp(?:eg|3))\s*(?:$|;)/i;this.useAltURL=!Q;Ha&&(c.useHTML5Audio=!0,c.preferFlash=!1,Ea&&(H=c.ignoreFlash=!0));var Ka;try{Ka=Audio!==g&&(Ga&&opera!==g&&10>opera.version()?new Audio(null):new Audio).canPlayType!==g}catch(pb){Ka=!1}this.hasHTML5=Ka;this.setup=function(a){var d=!c.url;a!==g&&(p&&B&&c.ok()&&(a.flashVersion!==g||a.url!==g))&&P(q("setupLate"));ta(a);d&&(V&&a.url!==g)&&c.beginDelayedInit();!V&&(a.url!==g&&"complete"===j.readyState)&&setTimeout(M,1);return c};
this.supported=this.ok=function(){return B?p&&!w:c.useHTML5Audio&&c.hasHTML5};this.getMovie=function(c){return A(c)||j[c]||i[c]};this.createSound=function(a,d){function e(){f=ia(f);c.sounds[f.id]=new La(f);c.soundIDs.push(f.id);return c.sounds[f.id]}var b,f;b=null;b="soundManager.createSound(): "+q(!p?"notReady":"notOK");if(!p||!c.ok())return P(b),!1;d!==g&&(a={id:a,url:d});f=x(a);f.url=la(f.url);f.id.toString().charAt(0).match(/^[0-9]$/)&&c._wD("soundManager.createSound(): "+q("badID",f.id),2);c._wD("soundManager.createSound(): "+
f.id+" ("+f.url+")",1);if(t(f.id,!0))return c._wD("soundManager.createSound(): "+f.id+" exists",1),c.sounds[f.id];ma(f)?(b=e(),c._wD("Creating sound "+f.id+", using HTML5"),b._setup_html5(f)):(8<k&&(null===f.isMovieStar&&(f.isMovieStar=!(!f.serverURL&&!(f.type&&f.type.match(fb)||f.url.match(nb)))),f.isMovieStar&&(c._wD("soundManager.createSound(): using MovieStar handling"),1<f.loops&&n("noNSLoop"))),f=ja(f,"soundManager.createSound(): "),b=e(),8===k?h._createSound(f.id,f.loops||1,f.usePolicyFile):
(h._createSound(f.id,f.url,f.usePeakData,f.useWaveformData,f.useEQData,f.isMovieStar,f.isMovieStar?f.bufferTime:!1,f.loops||1,f.serverURL,f.duration||null,f.autoPlay,!0,f.autoLoad,f.usePolicyFile),f.serverURL||(b.connected=!0,f.onconnect&&f.onconnect.apply(b))),!f.serverURL&&(f.autoLoad||f.autoPlay)&&b.load(f));!f.serverURL&&f.autoPlay&&b.play();return b};this.destroySound=function(a,d){if(!t(a))return!1;var e=c.sounds[a],b;e._iO={};e.stop();e.unload();for(b=0;b<c.soundIDs.length;b++)if(c.soundIDs[b]===
a){c.soundIDs.splice(b,1);break}d||e.destruct(!0);delete c.sounds[a];return!0};this.load=function(a,d){return!t(a)?!1:c.sounds[a].load(d)};this.unload=function(a){return!t(a)?!1:c.sounds[a].unload()};this.onposition=this.onPosition=function(a,d,e,b){return!t(a)?!1:c.sounds[a].onposition(d,e,b)};this.clearOnPosition=function(a,d,e){return!t(a)?!1:c.sounds[a].clearOnPosition(d,e)};this.start=this.play=function(a,d){var e=!1;return!p||!c.ok()?(P("soundManager.play(): "+q(!p?"notReady":"notOK")),e):!t(a)?
(d instanceof Object||(d={url:d}),d&&d.url&&(c._wD('soundManager.play(): attempting to create "'+a+'"',1),d.id=a,e=c.createSound(d).play()),e):c.sounds[a].play(d)};this.setPosition=function(a,d){return!t(a)?!1:c.sounds[a].setPosition(d)};this.stop=function(a){if(!t(a))return!1;c._wD("soundManager.stop("+a+")",1);return c.sounds[a].stop()};this.stopAll=function(){var a;c._wD("soundManager.stopAll()",1);for(a in c.sounds)c.sounds.hasOwnProperty(a)&&c.sounds[a].stop()};this.pause=function(a){return!t(a)?
!1:c.sounds[a].pause()};this.pauseAll=function(){var a;for(a=c.soundIDs.length-1;0<=a;a--)c.sounds[c.soundIDs[a]].pause()};this.resume=function(a){return!t(a)?!1:c.sounds[a].resume()};this.resumeAll=function(){var a;for(a=c.soundIDs.length-1;0<=a;a--)c.sounds[c.soundIDs[a]].resume()};this.togglePause=function(a){return!t(a)?!1:c.sounds[a].togglePause()};this.setPan=function(a,d){return!t(a)?!1:c.sounds[a].setPan(d)};this.setVolume=function(a,d){return!t(a)?!1:c.sounds[a].setVolume(d)};this.mute=function(a){var d=
0;a instanceof String&&(a=null);if(a){if(!t(a))return!1;c._wD('soundManager.mute(): Muting "'+a+'"');return c.sounds[a].mute()}c._wD("soundManager.mute(): Muting all sounds");for(d=c.soundIDs.length-1;0<=d;d--)c.sounds[c.soundIDs[d]].mute();return c.muted=!0};this.muteAll=function(){c.mute()};this.unmute=function(a){a instanceof String&&(a=null);if(a){if(!t(a))return!1;c._wD('soundManager.unmute(): Unmuting "'+a+'"');return c.sounds[a].unmute()}c._wD("soundManager.unmute(): Unmuting all sounds");
for(a=c.soundIDs.length-1;0<=a;a--)c.sounds[c.soundIDs[a]].unmute();c.muted=!1;return!0};this.unmuteAll=function(){c.unmute()};this.toggleMute=function(a){return!t(a)?!1:c.sounds[a].toggleMute()};this.getMemoryUse=function(){var c=0;h&&8!==k&&(c=parseInt(h._getMemoryUse(),10));return c};this.disable=function(a){var d;a===g&&(a=!1);if(w)return!1;w=!0;n("shutdown",1);for(d=c.soundIDs.length-1;0<=d;d--)Qa(c.sounds[c.soundIDs[d]]);U(a);s.remove(i,"load",K);return!0};this.canPlayMIME=function(a){var d;
c.hasHTML5&&(d=Z({type:a}));!d&&B&&(d=a&&c.ok()?!!(8<k&&a.match(fb)||a.match(c.mimePattern)):null);return d};this.canPlayURL=function(a){var d;c.hasHTML5&&(d=Z({url:a}));!d&&B&&(d=a&&c.ok()?!!a.match(c.filePattern):null);return d};this.canPlayLink=function(a){return a.type!==g&&a.type&&c.canPlayMIME(a.type)?!0:c.canPlayURL(a.href)};this.getSoundById=function(a,d){if(!a)throw Error("soundManager.getSoundById(): sID is null/undefined");var e=c.sounds[a];!e&&!d&&c._wD('"'+a+'" is an invalid sound ID.',
2);return e};this.onready=function(a,d){if("function"===typeof a)p&&c._wD(q("queue","onready")),d||(d=i),ua("onready",a,d),J();else throw q("needFunction","onready");return!0};this.ontimeout=function(a,d){if("function"===typeof a)p&&c._wD(q("queue","ontimeout")),d||(d=i),ua("ontimeout",a,d),J({type:"ontimeout"});else throw q("needFunction","ontimeout");return!0};this._wD=this._writeDebug=function(a,d,e){var b,f;if(!c.debugMode)return!1;e!==g&&e&&(a=a+" | "+(new Date).getTime());if(bb&&c.useConsole){e=
lb[d];if(console[e]!==g)console[e](a);else console.log(a);if(c.consoleOnly)return!0}try{b=A("soundmanager-debug");if(!b)return!1;f=j.createElement("div");0===++kb%2&&(f.className="sm2-alt");d=d===g?0:parseInt(d,10);f.appendChild(j.createTextNode(a));d&&(2<=d&&(f.style.fontWeight="bold"),3===d&&(f.style.color="#ff3333"));b.insertBefore(f,b.firstChild)}catch(h){}return!0};this._debug=function(){var a,d;n("currentObj",1);a=0;for(d=c.soundIDs.length;a<d;a++)c.sounds[c.soundIDs[a]]._debug()};this.reboot=
function(){c._wD("soundManager.reboot()");c.soundIDs.length&&c._wD("Destroying "+c.soundIDs.length+" SMSound objects...");var a,d;for(a=c.soundIDs.length-1;0<=a;a--)c.sounds[c.soundIDs[a]].destruct();if(h)try{F&&(ya=h.innerHTML),W=h.parentNode.removeChild(h),c._wD("Flash movie removed.")}catch(e){n("badRemove",2)}ya=W=B=null;c.enabled=V=p=X=Aa=S=T=w=c.swfLoaded=!1;c.soundIDs=[];c.sounds={};h=null;for(a in D)if(D.hasOwnProperty(a))for(d=D[a].length-1;0<=d;d--)D[a][d].fired=!1;c._wD("soundManager: Rebooting...");
i.setTimeout(c.beginDelayedInit,20)};this.getMoviePercent=function(){return h&&"PercentLoaded"in h?h.PercentLoaded():null};this.beginDelayedInit=function(){ba=!0;M();setTimeout(function(){if(Aa)return!1;ga();ea();return Aa=!0},20);L()};this.destruct=function(){c._wD("soundManager.destruct()");c.disable(!0)};La=function(a){var d,e,b=this,f,j,hb,m,i,p,r=!1,z=[],s=0,v,w,u=null;e=d=null;this.sID=this.id=a.id;this.url=a.url;this._iO=this.instanceOptions=this.options=x(a);this.pan=this.options.pan;this.volume=
this.options.volume;this.isHTML5=!1;this._a=null;this.id3={};this._debug=function(){if(c.debugMode){var a=null,d=[],e,f;for(a in b.options)null!==b.options[a]&&("function"===typeof b.options[a]?(e=b.options[a].toString(),e=e.replace(/\s\s+/g," "),f=e.indexOf("{"),d.push(" "+a+": {"+e.substr(f+1,Math.min(Math.max(e.indexOf("\n")-1,64),64)).replace(/\n/g,"")+"... }")):d.push(" "+a+": "+b.options[a]));c._wD("SMSound() merged options: {\n"+d.join(", \n")+"\n}")}};this._debug();this.load=function(a){var d=
null;a!==g?b._iO=x(a,b.options):(a=b.options,b._iO=a,u&&u!==b.url&&(n("manURL"),b._iO.url=b.url,b.url=null));b._iO.url||(b._iO.url=b.url);b._iO.url=la(b._iO.url);a=b.instanceOptions=b._iO;c._wD("SMSound.load(): "+a.url,1);if(a.url===b.url&&0!==b.readyState&&2!==b.readyState)return n("onURL",1),3===b.readyState&&a.onload&&a.onload.apply(b,[!!b.duration]),b;b.loaded=!1;b.readyState=1;b.playState=0;b.id3={};if(ma(a))d=b._setup_html5(a),d._called_load?c._wD(l+"ignoring request to load again: "+b.id):
(c._wD(l+"load: "+b.id),b._html5_canplay=!1,b.url!==a.url&&(c._wD(n("manURL")+": "+a.url),b._a.src=a.url,b.setPosition(0)),b._a.autobuffer="auto",b._a.preload="auto",b._a._called_load=!0,a.autoPlay&&b.play());else try{b.isHTML5=!1,b._iO=ja(ia(a)),a=b._iO,8===k?h._load(b.id,a.url,a.stream,a.autoPlay,a.usePolicyFile):h._load(b.id,a.url,!!a.stream,!!a.autoPlay,a.loops||1,!!a.autoLoad,a.usePolicyFile)}catch(e){n("smError",2),y("onload",!1),N({type:"SMSOUND_LOAD_JS_EXCEPTION",fatal:!0})}b.url=a.url;return b};
this.unload=function(){0!==b.readyState&&(c._wD('SMSound.unload(): "'+b.id+'"'),b.isHTML5?(m(),b._a&&(b._a.pause(),Ba(b._a,"about:blank"),u="about:blank")):8===k?h._unload(b.id,"about:blank"):h._unload(b.id),f());return b};this.destruct=function(a){c._wD('SMSound.destruct(): "'+b.id+'"');b.isHTML5?(m(),b._a&&(b._a.pause(),Ba(b._a),H||hb(),b._a._s=null,b._a=null)):(b._iO.onfailure=null,h._destroySound(b.id));a||c.destroySound(b.id,!0)};this.start=this.play=function(a,d){var e,f;f=!0;f=null;d=d===g?
!0:d;a||(a={});b.url&&(b._iO.url=b.url);b._iO=x(b._iO,b.options);b._iO=x(a,b._iO);b._iO.url=la(b._iO.url);b.instanceOptions=b._iO;if(b._iO.serverURL&&!b.connected)return b.getAutoPlay()||(c._wD("SMSound.play():  Netstream not connected yet - setting autoPlay"),b.setAutoPlay(!0)),b;ma(b._iO)&&(b._setup_html5(b._iO),i());1===b.playState&&!b.paused&&((e=b._iO.multiShot)?c._wD('SMSound.play(): "'+b.id+'" already playing (multi-shot)',1):(c._wD('SMSound.play(): "'+b.id+'" already playing (one-shot)',1),
f=b));if(null!==f)return f;a.url&&a.url!==b.url&&b.load(b._iO);b.loaded?c._wD('SMSound.play(): "'+b.id+'"'):0===b.readyState?(c._wD('SMSound.play(): Attempting to load "'+b.id+'"',1),b.isHTML5||(b._iO.autoPlay=!0),b.load(b._iO),b.instanceOptions=b._iO):2===b.readyState?(c._wD('SMSound.play(): Could not load "'+b.id+'" - exiting',2),f=b):c._wD('SMSound.play(): "'+b.id+'" is loading - attempting to play..',1);if(null!==f)return f;!b.isHTML5&&(9===k&&0<b.position&&b.position===b.duration)&&(c._wD('SMSound.play(): "'+
b.id+'": Sound at end, resetting to position:0'),a.position=0);if(b.paused&&0<=b.position&&(!b._iO.serverURL||0<b.position))c._wD('SMSound.play(): "'+b.id+'" is resuming from paused state',1),b.resume();else{b._iO=x(a,b._iO);if(null!==b._iO.from&&null!==b._iO.to&&0===b.instanceCount&&0===b.playState&&!b._iO.serverURL){e=function(){b._iO=x(a,b._iO);b.play(b._iO)};if(b.isHTML5&&!b._html5_canplay)c._wD('SMSound.play(): Beginning load of "'+b.id+'" for from/to case'),b.load({oncanplay:e}),f=!1;else if(!b.isHTML5&&
!b.loaded&&(!b.readyState||2!==b.readyState))c._wD('SMSound.play(): Preloading "'+b.id+'" for from/to case'),b.load({onload:e}),f=!1;if(null!==f)return f;b._iO=w()}c._wD('SMSound.play(): "'+b.id+'" is starting to play');(!b.instanceCount||b._iO.multiShotEvents||!b.isHTML5&&8<k&&!b.getAutoPlay())&&b.instanceCount++;b._iO.onposition&&0===b.playState&&p(b);b.playState=1;b.paused=!1;b.position=b._iO.position!==g&&!isNaN(b._iO.position)?b._iO.position:0;b.isHTML5||(b._iO=ja(ia(b._iO)));b._iO.onplay&&d&&
(b._iO.onplay.apply(b),r=!0);b.setVolume(b._iO.volume,!0);b.setPan(b._iO.pan,!0);b.isHTML5?(i(),f=b._setup_html5(),b.setPosition(b._iO.position),f.play()):(f=h._start(b.id,b._iO.loops||1,9===k?b._iO.position:b._iO.position/1E3,b._iO.multiShot),9===k&&!f&&(c._wD("SMSound.play(): "+b.id+": No sound hardware, or 32-sound ceiling hit"),b._iO.onplayerror&&b._iO.onplayerror.apply(b)))}return b};this.stop=function(a){var c=b._iO;1===b.playState&&(b._onbufferchange(0),b._resetOnPosition(0),b.paused=!1,b.isHTML5||
(b.playState=0),v(),c.to&&b.clearOnPosition(c.to),b.isHTML5?b._a&&(a=b.position,b.setPosition(0),b.position=a,b._a.pause(),b.playState=0,b._onTimer(),m()):(h._stop(b.id,a),c.serverURL&&b.unload()),b.instanceCount=0,b._iO={},c.onstop&&c.onstop.apply(b));return b};this.setAutoPlay=function(a){c._wD("sound "+b.id+" turned autoplay "+(a?"on":"off"));b._iO.autoPlay=a;b.isHTML5||(h._setAutoPlay(b.id,a),a&&(!b.instanceCount&&1===b.readyState)&&(b.instanceCount++,c._wD("sound "+b.id+" incremented instance count to "+
b.instanceCount)))};this.getAutoPlay=function(){return b._iO.autoPlay};this.setPosition=function(a){a===g&&(a=0);var d=b.isHTML5?Math.max(a,0):Math.min(b.duration||b._iO.duration,Math.max(a,0));b.position=d;a=b.position/1E3;b._resetOnPosition(b.position);b._iO.position=d;if(b.isHTML5){if(b._a)if(b._html5_canplay){if(b._a.currentTime!==a){c._wD("setPosition("+a+"): setting position");try{b._a.currentTime=a,(0===b.playState||b.paused)&&b._a.pause()}catch(e){c._wD("setPosition("+a+"): setting position failed: "+
e.message,2)}}}else c._wD("setPosition("+a+"): delaying, sound not ready")}else a=9===k?b.position:a,b.readyState&&2!==b.readyState&&h._setPosition(b.id,a,b.paused||!b.playState,b._iO.multiShot);b.isHTML5&&b.paused&&b._onTimer(!0);return b};this.pause=function(a){if(b.paused||0===b.playState&&1!==b.readyState)return b;c._wD("SMSound.pause()");b.paused=!0;b.isHTML5?(b._setup_html5().pause(),m()):(a||a===g)&&h._pause(b.id,b._iO.multiShot);b._iO.onpause&&b._iO.onpause.apply(b);return b};this.resume=
function(){var a=b._iO;if(!b.paused)return b;c._wD("SMSound.resume()");b.paused=!1;b.playState=1;b.isHTML5?(b._setup_html5().play(),i()):(a.isMovieStar&&!a.serverURL&&b.setPosition(b.position),h._pause(b.id,a.multiShot));!r&&a.onplay?(a.onplay.apply(b),r=!0):a.onresume&&a.onresume.apply(b);return b};this.togglePause=function(){c._wD("SMSound.togglePause()");if(0===b.playState)return b.play({position:9===k&&!b.isHTML5?b.position:b.position/1E3}),b;b.paused?b.resume():b.pause();return b};this.setPan=
function(a,c){a===g&&(a=0);c===g&&(c=!1);b.isHTML5||h._setPan(b.id,a);b._iO.pan=a;c||(b.pan=a,b.options.pan=a);return b};this.setVolume=function(a,d){a===g&&(a=100);d===g&&(d=!1);b.isHTML5?b._a&&(b._a.volume=Math.max(0,Math.min(1,a/100))):h._setVolume(b.id,c.muted&&!b.muted||b.muted?0:a);b._iO.volume=a;d||(b.volume=a,b.options.volume=a);return b};this.mute=function(){b.muted=!0;b.isHTML5?b._a&&(b._a.muted=!0):h._setVolume(b.id,0);return b};this.unmute=function(){b.muted=!1;var a=b._iO.volume!==g;
b.isHTML5?b._a&&(b._a.muted=!1):h._setVolume(b.id,a?b._iO.volume:b.options.volume);return b};this.toggleMute=function(){return b.muted?b.unmute():b.mute()};this.onposition=this.onPosition=function(a,c,d){z.push({position:parseInt(a,10),method:c,scope:d!==g?d:b,fired:!1});return b};this.clearOnPosition=function(b,a){var c,b=parseInt(b,10);if(isNaN(b))return!1;for(c=0;c<z.length;c++)if(b===z[c].position&&(!a||a===z[c].method))z[c].fired&&s--,z.splice(c,1)};this._processOnPosition=function(){var a,c;
a=z.length;if(!a||!b.playState||s>=a)return!1;for(a-=1;0<=a;a--)c=z[a],!c.fired&&b.position>=c.position&&(c.fired=!0,s++,c.method.apply(c.scope,[c.position]));return!0};this._resetOnPosition=function(b){var a,c;a=z.length;if(!a)return!1;for(a-=1;0<=a;a--)c=z[a],c.fired&&b<=c.position&&(c.fired=!1,s--);return!0};w=function(){var a=b._iO,d=a.from,e=a.to,f,g;g=function(){c._wD(b.id+': "to" time of '+e+" reached.");b.clearOnPosition(e,g);b.stop()};f=function(){c._wD(b.id+': playing "from" '+d);if(null!==
e&&!isNaN(e))b.onPosition(e,g)};null!==d&&!isNaN(d)&&(a.position=d,a.multiShot=!1,f());return a};p=function(){var a,c=b._iO.onposition;if(c)for(a in c)if(c.hasOwnProperty(a))b.onPosition(parseInt(a,10),c[a])};v=function(){var a,c=b._iO.onposition;if(c)for(a in c)c.hasOwnProperty(a)&&b.clearOnPosition(parseInt(a,10))};i=function(){b.isHTML5&&Ta(b)};m=function(){b.isHTML5&&Ua(b)};f=function(a){a||(z=[],s=0);r=!1;b._hasTimer=null;b._a=null;b._html5_canplay=!1;b.bytesLoaded=null;b.bytesTotal=null;b.duration=
b._iO&&b._iO.duration?b._iO.duration:null;b.durationEstimate=null;b.buffered=[];b.eqData=[];b.eqData.left=[];b.eqData.right=[];b.failures=0;b.isBuffering=!1;b.instanceOptions={};b.instanceCount=0;b.loaded=!1;b.metadata={};b.readyState=0;b.muted=!1;b.paused=!1;b.peakData={left:0,right:0};b.waveformData={left:[],right:[]};b.playState=0;b.position=null;b.id3={}};f();this._onTimer=function(a){var c,f=!1,g={};if(b._hasTimer||a){if(b._a&&(a||(0<b.playState||1===b.readyState)&&!b.paused))c=b._get_html5_duration(),
c!==d&&(d=c,b.duration=c,f=!0),b.durationEstimate=b.duration,c=1E3*b._a.currentTime||0,c!==e&&(e=c,f=!0),(f||a)&&b._whileplaying(c,g,g,g,g);return f}};this._get_html5_duration=function(){var a=b._iO;return(a=b._a&&b._a.duration?1E3*b._a.duration:a&&a.duration?a.duration:null)&&!isNaN(a)&&Infinity!==a?a:null};this._apply_loop=function(b,a){!b.loop&&1<a&&c._wD("Note: Native HTML5 looping is infinite.");b.loop=1<a?"loop":""};this._setup_html5=function(a){var a=x(b._iO,a),c=decodeURI,d=H?Ma:b._a,e=c(a.url),
g;H?e===Za&&(g=!0):e===u&&(g=!0);if(d){if(d._s)if(H)d._s&&(d._s.playState&&!g)&&d._s.stop();else if(!H&&e===c(u))return b._apply_loop(d,a.loops),d;g||(f(!1),d.src=a.url,Za=u=b.url=a.url,d._called_load=!1)}else n("h5a"),b._a=a.autoLoad||a.autoPlay?new Audio(a.url):Ga&&10>opera.version()?new Audio(null):new Audio,d=b._a,d._called_load=!1,H&&(Ma=d);b.isHTML5=!0;b._a=d;d._s=b;j();b._apply_loop(d,a.loops);a.autoLoad||a.autoPlay?b.load():(d.autobuffer=!1,d.preload="auto");return d};j=function(){if(b._a._added_events)return!1;
var a;b._a._added_events=!0;for(a in C)C.hasOwnProperty(a)&&b._a&&b._a.addEventListener(a,C[a],!1);return!0};hb=function(){var a;c._wD(l+"removing event listeners: "+b.id);b._a._added_events=!1;for(a in C)C.hasOwnProperty(a)&&b._a&&b._a.removeEventListener(a,C[a],!1)};this._onload=function(a){a=!!a||!b.isHTML5&&8===k&&b.duration;c._wD('SMSound._onload(): "'+b.id+'"'+(a?" loaded.":" failed to load? - "+b.url),a?1:2);!a&&!b.isHTML5&&(!0===c.sandbox.noRemote&&c._wD("SMSound._onload(): "+q("noNet"),1),
!0===c.sandbox.noLocal&&c._wD("SMSound._onload(): "+q("noLocal"),1));b.loaded=a;b.readyState=a?3:2;b._onbufferchange(0);b._iO.onload&&b._iO.onload.apply(b,[a]);return!0};this._onbufferchange=function(a){if(0===b.playState||a&&b.isBuffering||!a&&!b.isBuffering)return!1;b.isBuffering=1===a;b._iO.onbufferchange&&(c._wD("SMSound._onbufferchange(): "+a),b._iO.onbufferchange.apply(b));return!0};this._onsuspend=function(){b._iO.onsuspend&&(c._wD("SMSound._onsuspend()"),b._iO.onsuspend.apply(b));return!0};
this._onfailure=function(a,d,e){b.failures++;c._wD('SMSound._onfailure(): "'+b.id+'" count '+b.failures);if(b._iO.onfailure&&1===b.failures)b._iO.onfailure(b,a,d,e);else c._wD("SMSound._onfailure(): ignoring")};this._onfinish=function(){var a=b._iO.onfinish;b._onbufferchange(0);b._resetOnPosition(0);if(b.instanceCount&&(b.instanceCount--,b.instanceCount||(v(),b.playState=0,b.paused=!1,b.instanceCount=0,b.instanceOptions={},b._iO={},m(),b.isHTML5&&(b.position=0)),(!b.instanceCount||b._iO.multiShotEvents)&&
a))c._wD('SMSound._onfinish(): "'+b.id+'"'),a.apply(b)};this._whileloading=function(a,c,d,e){var f=b._iO;b.bytesLoaded=a;b.bytesTotal=c;b.duration=Math.floor(d);b.bufferLength=e;b.durationEstimate=!b.isHTML5&&!f.isMovieStar?f.duration?b.duration>f.duration?b.duration:f.duration:parseInt(b.bytesTotal/b.bytesLoaded*b.duration,10):b.duration;b.isHTML5||(b.buffered=[{start:0,end:b.duration}]);(3!==b.readyState||b.isHTML5)&&f.whileloading&&f.whileloading.apply(b)};this._whileplaying=function(a,c,d,e,f){var m=
b._iO;if(isNaN(a)||null===a)return!1;b.position=Math.max(0,a);b._processOnPosition();!b.isHTML5&&8<k&&(m.usePeakData&&(c!==g&&c)&&(b.peakData={left:c.leftPeak,right:c.rightPeak}),m.useWaveformData&&(d!==g&&d)&&(b.waveformData={left:d.split(","),right:e.split(",")}),m.useEQData&&(f!==g&&f&&f.leftEQ)&&(a=f.leftEQ.split(","),b.eqData=a,b.eqData.left=a,f.rightEQ!==g&&f.rightEQ&&(b.eqData.right=f.rightEQ.split(","))));1===b.playState&&(!b.isHTML5&&(8===k&&!b.position&&b.isBuffering)&&b._onbufferchange(0),
m.whileplaying&&m.whileplaying.apply(b));return!0};this._oncaptiondata=function(a){c._wD('SMSound._oncaptiondata(): "'+this.id+'" caption data received.');b.captiondata=a;b._iO.oncaptiondata&&b._iO.oncaptiondata.apply(b,[a])};this._onmetadata=function(a,d){c._wD('SMSound._onmetadata(): "'+this.id+'" metadata received.');var e={},f,g;f=0;for(g=a.length;f<g;f++)e[a[f]]=d[f];b.metadata=e;b._iO.onmetadata&&b._iO.onmetadata.apply(b)};this._onid3=function(a,d){c._wD('SMSound._onid3(): "'+this.id+'" ID3 data received.');
var e=[],f,g;f=0;for(g=a.length;f<g;f++)e[a[f]]=d[f];b.id3=x(b.id3,e);b._iO.onid3&&b._iO.onid3.apply(b)};this._onconnect=function(a){a=1===a;c._wD('SMSound._onconnect(): "'+b.id+'"'+(a?" connected.":" failed to connect? - "+b.url),a?1:2);if(b.connected=a)b.failures=0,t(b.id)&&(b.getAutoPlay()?b.play(g,b.getAutoPlay()):b._iO.autoLoad&&b.load()),b._iO.onconnect&&b._iO.onconnect.apply(b,[a])};this._ondataerror=function(a){0<b.playState&&(c._wD("SMSound._ondataerror(): "+a),b._iO.ondataerror&&b._iO.ondataerror.apply(b))}};
fa=function(){return j.body||j._docElement||j.getElementsByTagName("div")[0]};A=function(a){return j.getElementById(a)};x=function(a,d){var e=a||{},b,f;b=d===g?c.defaultOptions:d;for(f in b)b.hasOwnProperty(f)&&e[f]===g&&(e[f]="object"!==typeof b[f]||null===b[f]?b[f]:x(e[f],b[f]));return e};I={onready:1,ontimeout:1,defaultOptions:1,flash9Options:1,movieStarOptions:1};ta=function(a,d){var e,b=!0,f=d!==g,h=c.setupOptions;if(a===g){b=[];for(e in h)h.hasOwnProperty(e)&&b.push(e);for(e in I)I.hasOwnProperty(e)&&
("object"===typeof c[e]?b.push(e+": {...}"):c[e]instanceof Function?b.push(e+": function() {...}"):b.push(e));c._wD(q("setup",b.join(", ")));return!1}for(e in a)if(a.hasOwnProperty(e))if("object"!==typeof a[e]||null===a[e]||a[e]instanceof Array)f&&I[d]!==g?c[d][e]=a[e]:h[e]!==g?(c.setupOptions[e]=a[e],c[e]=a[e]):I[e]===g?(P(q(c[e]===g?"setupUndef":"setupError",e),2),b=!1):c[e]instanceof Function?c[e].apply(c,a[e]instanceof Array?a[e]:[a[e]]):c[e]=a[e];else if(I[e]===g)P(q(c[e]===g?"setupUndef":"setupError",
e),2),b=!1;else return ta(a[e],e);return b};var ib=function(a){var a=Ya.call(a),c=a.length;oa?(a[1]="on"+a[1],3<c&&a.pop()):3===c&&a.push(!1);return a},jb=function(a,c){var e=a.shift(),b=[ob[c]];if(oa)e[b](a[0],a[1]);else e[b].apply(e,a)},oa=i.attachEvent,ob={add:oa?"attachEvent":"addEventListener",remove:oa?"detachEvent":"removeEventListener"};s={add:function(){jb(ib(arguments),"add")},remove:function(){jb(ib(arguments),"remove")}};C={abort:r(function(){c._wD(l+"abort: "+this._s.id)}),canplay:r(function(){var a=
this._s,d;if(a._html5_canplay)return!0;a._html5_canplay=!0;c._wD(l+"canplay: "+a.id+", "+a.url);a._onbufferchange(0);d=a._iO.position!==g&&!isNaN(a._iO.position)?a._iO.position/1E3:null;if(a.position&&this.currentTime!==d){c._wD(l+"canplay: setting position to "+d);try{this.currentTime=d}catch(e){c._wD(l+"setting position of "+d+" failed: "+e.message,2)}}a._iO._oncanplay&&a._iO._oncanplay()}),canplaythrough:r(function(){var a=this._s;a.loaded||(a._onbufferchange(0),a._whileloading(a.bytesLoaded,a.bytesTotal,
a._get_html5_duration()),a._onload(!0))}),ended:r(function(){var a=this._s;c._wD(l+"ended: "+a.id);a._onfinish()}),error:r(function(){c._wD(l+"error: "+this.error.code);this._s._onload(!1)}),loadeddata:r(function(){var a=this._s;c._wD(l+"loadeddata: "+a.id);!a._loaded&&!Fa&&(a.duration=a._get_html5_duration())}),loadedmetadata:r(function(){c._wD(l+"loadedmetadata: "+this._s.id)}),loadstart:r(function(){c._wD(l+"loadstart: "+this._s.id);this._s._onbufferchange(1)}),play:r(function(){c._wD(l+"play: "+
this._s.id+", "+this._s.url);this._s._onbufferchange(0)}),playing:r(function(){c._wD(l+"playing: "+this._s.id);this._s._onbufferchange(0)}),progress:r(function(a){var d=this._s,e,b,f;e=0;var g="progress"===a.type,h=a.target.buffered,m=a.loaded||0,j=a.total||1;d.buffered=[];if(h&&h.length){e=0;for(b=h.length;e<b;e++)d.buffered.push({start:1E3*h.start(e),end:1E3*h.end(e)});e=1E3*(h.end(0)-h.start(0));m=e/(1E3*a.target.duration);if(g&&1<h.length){f=[];b=h.length;for(e=0;e<b;e++)f.push(1E3*a.target.buffered.start(e)+
"-"+1E3*a.target.buffered.end(e));c._wD(l+"progress: timeRanges: "+f.join(", "))}g&&!isNaN(m)&&c._wD(l+"progress: "+d.id+": "+Math.floor(100*m)+"% loaded")}isNaN(m)||(d._onbufferchange(0),d._whileloading(m,j,d._get_html5_duration()),m&&(j&&m===j)&&C.canplaythrough.call(this,a))}),ratechange:r(function(){c._wD(l+"ratechange: "+this._s.id)}),suspend:r(function(a){var d=this._s;c._wD(l+"suspend: "+d.id);C.progress.call(this,a);d._onsuspend()}),stalled:r(function(){c._wD(l+"stalled: "+this._s.id)}),timeupdate:r(function(){this._s._onTimer()}),
waiting:r(function(){var a=this._s;c._wD(l+"waiting: "+a.id);a._onbufferchange(1)})};ma=function(a){return a.serverURL||a.type&&aa(a.type)?!1:a.type?Z({type:a.type}):Z({url:a.url})||c.html5Only};Ba=function(a,c){a&&(a.src=c)};Z=function(a){if(!c.useHTML5Audio||!c.hasHTML5)return!1;var d=a.url||null,a=a.type||null,e=c.audioFormats,b;if(a&&c.html5[a]!==g)return c.html5[a]&&!aa(a);if(!E){E=[];for(b in e)e.hasOwnProperty(b)&&(E.push(b),e[b].related&&(E=E.concat(e[b].related)));E=RegExp("\\.("+E.join("|")+
")(\\?.*)?$","i")}b=d?d.toLowerCase().match(E):null;!b||!b.length?a&&(d=a.indexOf(";"),b=(-1!==d?a.substr(0,d):a).substr(6)):b=b[1];b&&c.html5[b]!==g?d=c.html5[b]&&!aa(b):(a="audio/"+b,d=c.html5.canPlayType({type:a}),d=(c.html5[b]=d)&&c.html5[a]&&!aa(a));return d};Xa=function(){function a(a){var b,e,f=b=!1;if(!d||"function"!==typeof d.canPlayType)return b;if(a instanceof Array){b=0;for(e=a.length;b<e;b++)if(c.html5[a[b]]||d.canPlayType(a[b]).match(c.html5Test))f=!0,c.html5[a[b]]=!0,c.flash[a[b]]=
!!a[b].match(db);b=f}else a=d&&"function"===typeof d.canPlayType?d.canPlayType(a):!1,b=!(!a||!a.match(c.html5Test));return b}if(!c.useHTML5Audio||!c.hasHTML5)return!1;var d=Audio!==g?Ga&&10>opera.version()?new Audio(null):new Audio:null,e,b,f={},h;h=c.audioFormats;for(e in h)if(h.hasOwnProperty(e)&&(b="audio/"+e,f[e]=a(h[e].type),f[b]=f[e],e.match(db)?(c.flash[e]=!0,c.flash[b]=!0):(c.flash[e]=!1,c.flash[b]=!1),h[e]&&h[e].related))for(b=h[e].related.length-1;0<=b;b--)f["audio/"+h[e].related[b]]=f[e],
c.html5[h[e].related[b]]=f[e],c.flash[h[e].related[b]]=f[e];f.canPlayType=d?a:null;c.html5=x(c.html5,f);return!0};da={notReady:"Not loaded yet - wait for soundManager.onready()",notOK:"Audio support is not available.",domError:"soundManager::createMovie(): appendChild/innerHTML call failed. DOM not ready or other error.",spcWmode:"soundManager::createMovie(): Removing wmode, preventing known SWF loading issue(s)",swf404:"soundManager: Verify that %s is a valid path.",tryDebug:"Try soundManager.debugFlash = true for more security details (output goes to SWF.)",
checkSWF:"See SWF output for more debug info.",localFail:"soundManager: Non-HTTP page ("+j.location.protocol+" URL?) Review Flash player security settings for this special case:\nhttp://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html\nMay need to add/allow path, eg. c:/sm2/ or /users/me/sm2/",waitFocus:"soundManager: Special case: Waiting for SWF to load with window focus...",waitImpatient:"soundManager: Getting impatient, still waiting for Flash%s...",waitForever:"soundManager: Waiting indefinitely for Flash (will recover if unblocked)...",
waitSWF:"soundManager: Retrying, waiting for 100% SWF load...",needFunction:"soundManager: Function object expected for %s",badID:'Warning: Sound ID "%s" should be a string, starting with a non-numeric character',currentObj:"--- soundManager._debug(): Current sound objects ---",waitEI:"soundManager::initMovie(): Waiting for ExternalInterface call from Flash...",waitOnload:"soundManager: Waiting for window.onload()",docLoaded:"soundManager: Document already loaded",onload:"soundManager::initComplete(): calling soundManager.onload()",
onloadOK:"soundManager.onload() complete",init:"soundManager::init()",didInit:"soundManager::init(): Already called?",flashJS:"soundManager: Attempting JS to Flash call...",secNote:"Flash security note: Network/internet URLs will not load due to security restrictions. Access can be configured via Flash Player Global Security Settings Page: http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html",badRemove:"Warning: Failed to remove flash movie.",shutdown:"soundManager.disable(): Shutting down",
queue:"soundManager: Queueing %s handler",smFail:"soundManager: Failed to initialise.",smError:"SMSound.load(): Exception: JS-Flash communication failed, or JS error.",fbTimeout:"No flash response, applying .swf_timedout CSS...",fbLoaded:"Flash loaded",fbHandler:"soundManager::flashBlockHandler()",manURL:"SMSound.load(): Using manually-assigned URL",onURL:"soundManager.load(): current URL already assigned.",badFV:'soundManager.flashVersion must be 8 or 9. "%s" is invalid. Reverting to %s.',as2loop:"Note: Setting stream:false so looping can work (flash 8 limitation)",
noNSLoop:"Note: Looping not implemented for MovieStar formats",needfl9:"Note: Switching to flash 9, required for MP4 formats.",mfTimeout:"Setting flashLoadTimeout = 0 (infinite) for off-screen, mobile flash case",needFlash:"soundManager: Fatal error: Flash is needed to play some required formats, but is not available.",gotFocus:"soundManager: Got window focus.",mfOn:"mobileFlash::enabling on-screen flash repositioning",policy:"Enabling usePolicyFile for data access",setup:"soundManager.setup(): allowed parameters: %s",
setupError:'soundManager.setup(): "%s" cannot be assigned with this method.',setupUndef:'soundManager.setup(): Could not find option "%s"',setupLate:"soundManager.setup(): url + flashVersion changes will not take effect until reboot().",h5a:"creating HTML5 Audio() object",noURL:"soundManager: Flash URL required. Call soundManager.setup({url:...}) to get started."};q=function(){var a=Ya.call(arguments),c=a.shift(),c=da&&da[c]?da[c]:"",e,b;if(c&&a&&a.length){e=0;for(b=a.length;e<b;e++)c=c.replace("%s",
a[e])}return c};ia=function(a){8===k&&(1<a.loops&&a.stream)&&(n("as2loop"),a.stream=!1);return a};ja=function(a,d){if(a&&!a.usePolicyFile&&(a.onid3||a.usePeakData||a.useWaveformData||a.useEQData))c._wD((d||"")+q("policy")),a.usePolicyFile=!0;return a};P=function(a){console!==g&&console.warn!==g?console.warn(a):c._wD(a)};qa=function(){return!1};Qa=function(a){for(var c in a)a.hasOwnProperty(c)&&"function"===typeof a[c]&&(a[c]=qa)};ha=function(a){a===g&&(a=!1);if(w||a)n("smFail",2),c.disable(a)};Ra=
function(a){var d=null;if(a)if(a.match(/\.swf(\?.*)?$/i)){if(d=a.substr(a.toLowerCase().lastIndexOf(".swf?")+4))return a}else a.lastIndexOf("/")!==a.length-1&&(a+="/");a=(a&&-1!==a.lastIndexOf("/")?a.substr(0,a.lastIndexOf("/")+1):"./")+c.movieURL;c.noSWFCache&&(a+="?ts="+(new Date).getTime());return a};va=function(){k=parseInt(c.flashVersion,10);8!==k&&9!==k&&(c._wD(q("badFV",k,8)),c.flashVersion=k=8);var a=c.debugMode||c.debugFlash?"_debug.swf":".swf";c.useHTML5Audio&&(!c.html5Only&&c.audioFormats.mp4.required&&
9>k)&&(c._wD(q("needfl9")),c.flashVersion=k=9);c.version=c.versionNumber+(c.html5Only?" (HTML5-only mode)":9===k?" (AS3/Flash 9)":" (AS2/Flash 8)");8<k?(c.defaultOptions=x(c.defaultOptions,c.flash9Options),c.features.buffering=!0,c.defaultOptions=x(c.defaultOptions,c.movieStarOptions),c.filePatterns.flash9=RegExp("\\.(mp3|"+gb.join("|")+")(\\?.*)?$","i"),c.features.movieStar=!0):c.features.movieStar=!1;c.filePattern=c.filePatterns[8!==k?"flash9":"flash8"];c.movieURL=(8===k?"soundmanager2.swf":"soundmanager2_flash9.swf").replace(".swf",
a);c.features.peakData=c.features.waveformData=c.features.eqData=8<k};Pa=function(a,c){if(!h)return!1;h._setPolling(a,c)};xa=function(){c.debugURLParam.test(R)&&(c.debugMode=!0);if(A(c.debugID))return!1;var a,d,e,b;if(c.debugMode&&!A(c.debugID)&&(!bb||!c.useConsole||!c.consoleOnly)){a=j.createElement("div");a.id=c.debugID+"-toggle";d={position:"fixed",bottom:"0px",right:"0px",width:"1.2em",height:"1.2em",lineHeight:"1.2em",margin:"2px",textAlign:"center",border:"1px solid #999",cursor:"pointer",background:"#fff",
color:"#333",zIndex:10001};a.appendChild(j.createTextNode("-"));a.onclick=Sa;a.title="Toggle SM2 debug console";v.match(/msie 6/i)&&(a.style.position="absolute",a.style.cursor="hand");for(b in d)d.hasOwnProperty(b)&&(a.style[b]=d[b]);d=j.createElement("div");d.id=c.debugID;d.style.display=c.debugMode?"block":"none";if(c.debugMode&&!A(a.id)){try{e=fa(),e.appendChild(a)}catch(f){throw Error(q("domError")+" \n"+f.toString());}e.appendChild(d)}}};t=this.getSoundById;n=function(a,d){return!a?"":c._wD(q(a),
d)};R.indexOf("sm2-debug=alert")+1&&c.debugMode&&(c._wD=function(a){G.alert(a)});Sa=function(){var a=A(c.debugID),d=A(c.debugID+"-toggle");if(!a)return!1;sa?(d.innerHTML="+",a.style.display="none"):(d.innerHTML="-",a.style.display="block");sa=!sa};y=function(a,c,e){if(i.sm2Debugger!==g)try{sm2Debugger.handleEvent(a,c,e)}catch(b){}return!0};O=function(){var a=[];c.debugMode&&a.push("sm2_debug");c.debugFlash&&a.push("flash_debug");c.useHighPerformance&&a.push("high_performance");return a.join(" ")};
za=function(){var a=q("fbHandler"),d=c.getMoviePercent(),e={type:"FLASHBLOCK"};if(c.html5Only)return!1;c.ok()?(c.didFlashBlock&&c._wD(a+": Unblocked"),c.oMC&&(c.oMC.className=[O(),"movieContainer","swf_loaded"+(c.didFlashBlock?" swf_unblocked":"")].join(" "))):(B&&(c.oMC.className=O()+" movieContainer "+(null===d?"swf_timedout":"swf_error"),c._wD(a+": "+q("fbTimeout")+(d?" ("+q("fbLoaded")+")":""))),c.didFlashBlock=!0,J({type:"ontimeout",ignoreInit:!0,error:e}),N(e))};ua=function(a,c,e){D[a]===g&&
(D[a]=[]);D[a].push({method:c,scope:e||null,fired:!1})};J=function(a){a||(a={type:c.ok()?"onready":"ontimeout"});if(!p&&a&&!a.ignoreInit||"ontimeout"===a.type&&(c.ok()||w&&!a.ignoreInit))return!1;var d={success:a&&a.ignoreInit?c.ok():!w},e=a&&a.type?D[a.type]||[]:[],b=[],f,g=[d],h=B&&c.useFlashBlock&&!c.ok();a.error&&(g[0].error=a.error);d=0;for(f=e.length;d<f;d++)!0!==e[d].fired&&b.push(e[d]);if(b.length){c._wD("soundManager: Firing "+b.length+" "+a.type+"() item"+(1===b.length?"":"s"));d=0;for(f=
b.length;d<f;d++)b[d].scope?b[d].method.apply(b[d].scope,g):b[d].method.apply(this,g),h||(b[d].fired=!0)}return!0};K=function(){i.setTimeout(function(){c.useFlashBlock&&za();J();"function"===typeof c.onload&&(n("onload",1),c.onload.apply(i),n("onloadOK",1));c.waitForWindowLoad&&s.add(i,"load",K)},1)};Da=function(){if(u!==g)return u;var a=!1,c=navigator,e=c.plugins,b,f=i.ActiveXObject;if(e&&e.length)(c=c.mimeTypes)&&(c["application/x-shockwave-flash"]&&c["application/x-shockwave-flash"].enabledPlugin&&
c["application/x-shockwave-flash"].enabledPlugin.description)&&(a=!0);else if(f!==g&&!v.match(/MSAppHost/i)){try{b=new f("ShockwaveFlash.ShockwaveFlash")}catch(h){}a=!!b}return u=a};Wa=function(){var a,d,e=c.audioFormats;if(Ea&&v.match(/os (1|2|3_0|3_1)/i))c.hasHTML5=!1,c.html5Only=!0,c.oMC&&(c.oMC.style.display="none");else if(c.useHTML5Audio){if(!c.html5||!c.html5.canPlayType)c._wD("SoundManager: No HTML5 Audio() support detected."),c.hasHTML5=!1;Ia&&c._wD("soundManager::Note: Buggy HTML5 Audio in Safari on this OS X release, see https://bugs.webkit.org/show_bug.cgi?id=32159 - "+
(!u?" would use flash fallback for MP3/MP4, but none detected.":"will use flash fallback for MP3/MP4, if available"),1)}if(c.useHTML5Audio&&c.hasHTML5)for(d in e)if(e.hasOwnProperty(d)&&(e[d].required&&!c.html5.canPlayType(e[d].type)||c.preferFlash&&(c.flash[d]||c.flash[e[d].type])))a=!0;c.ignoreFlash&&(a=!1);c.html5Only=c.hasHTML5&&c.useHTML5Audio&&!a;return!c.html5Only};la=function(a){var d,e,b=0;if(a instanceof Array){d=0;for(e=a.length;d<e;d++)if(a[d]instanceof Object){if(c.canPlayMIME(a[d].type)){b=
d;break}}else if(c.canPlayURL(a[d])){b=d;break}a[b].url&&(a[b]=a[b].url);a=a[b]}return a};Ta=function(a){a._hasTimer||(a._hasTimer=!0,!Ha&&c.html5PollingInterval&&(null===Y&&0===ka&&(Y=i.setInterval(Va,c.html5PollingInterval)),ka++))};Ua=function(a){a._hasTimer&&(a._hasTimer=!1,!Ha&&c.html5PollingInterval&&ka--)};Va=function(){var a;if(null!==Y&&!ka)return i.clearInterval(Y),Y=null,!1;for(a=c.soundIDs.length-1;0<=a;a--)c.sounds[c.soundIDs[a]].isHTML5&&c.sounds[c.soundIDs[a]]._hasTimer&&c.sounds[c.soundIDs[a]]._onTimer()};
N=function(a){a=a!==g?a:{};"function"===typeof c.onerror&&c.onerror.apply(i,[{type:a.type!==g?a.type:null}]);a.fatal!==g&&a.fatal&&c.disable()};$a=function(){if(!Ia||!Da())return!1;var a=c.audioFormats,d,e;for(e in a)if(a.hasOwnProperty(e)&&("mp3"===e||"mp4"===e))if(c._wD("soundManager: Using flash fallback for "+e+" format"),c.html5[e]=!1,a[e]&&a[e].related)for(d=a[e].related.length-1;0<=d;d--)c.html5[a[e].related[d]]=!1};this._setSandboxType=function(a){var d=c.sandbox;d.type=a;d.description=d.types[d.types[a]!==
g?a:"unknown"];c._wD("Flash security sandbox type: "+d.type);"localWithFile"===d.type?(d.noRemote=!0,d.noLocal=!1,n("secNote",2)):"localWithNetwork"===d.type?(d.noRemote=!1,d.noLocal=!0):"localTrusted"===d.type&&(d.noRemote=!1,d.noLocal=!1)};this._externalInterfaceOK=function(a,d){if(c.swfLoaded)return!1;var e,b=(new Date).getTime();c._wD("soundManager::externalInterfaceOK()"+(a?" (~"+(b-a)+" ms)":""));y("swf",!0);y("flashtojs",!0);c.swfLoaded=!0;na=!1;Ia&&$a();if(!d||d.replace(/\+dev/i,"")!==c.versionNumber.replace(/\+dev/i,
""))return e='soundManager: Fatal: JavaScript file build "'+c.versionNumber+'" does not match Flash SWF build "'+d+'" at '+c.url+". Ensure both are up-to-date.",setTimeout(function(){throw Error(e);},0),!1;setTimeout(ra,F?100:1)};ga=function(a,d){function e(){c._wD("-- SoundManager 2 "+c.version+(!c.html5Only&&c.useHTML5Audio?c.hasHTML5?" + HTML5 audio":", no HTML5 audio support":"")+(!c.html5Only?(c.useHighPerformance?", high performance mode, ":", ")+((c.flashPollingInterval?"custom ("+c.flashPollingInterval+
"ms)":"normal")+" polling")+(c.wmode?", wmode: "+c.wmode:"")+(c.debugFlash?", flash debug mode":"")+(c.useFlashBlock?", flashBlock mode":""):"")+" --",1)}function b(a,b){return'<param name="'+a+'" value="'+b+'" />'}if(S&&T)return!1;if(c.html5Only)return va(),e(),c.oMC=A(c.movieID),ra(),T=S=!0,!1;var f=d||c.url,h=c.altURL||f,i=fa(),m=O(),k=null,k=j.getElementsByTagName("html")[0],l,r,p,k=k&&k.dir&&k.dir.match(/rtl/i),a=a===g?c.id:a;va();c.url=Ra(Q?f:h);d=c.url;c.wmode=!c.wmode&&c.useHighPerformance?
"transparent":c.wmode;if(null!==c.wmode&&(v.match(/msie 8/i)||!F&&!c.useHighPerformance)&&navigator.platform.match(/win32|win64/i))n("spcWmode"),c.wmode=null;i={name:a,id:a,src:d,quality:"high",allowScriptAccess:c.allowScriptAccess,bgcolor:c.bgColor,pluginspage:eb+"www.macromedia.com/go/getflashplayer",title:"JS/Flash audio component (SoundManager 2)",type:"application/x-shockwave-flash",wmode:c.wmode,hasPriority:"true"};c.debugFlash&&(i.FlashVars="debug=1");c.wmode||delete i.wmode;if(F)f=j.createElement("div"),
r=['<object id="'+a+'" data="'+d+'" type="'+i.type+'" title="'+i.title+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="'+eb+'download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0">',b("movie",d),b("AllowScriptAccess",c.allowScriptAccess),b("quality",i.quality),c.wmode?b("wmode",c.wmode):"",b("bgcolor",c.bgColor),b("hasPriority","true"),c.debugFlash?b("FlashVars",i.FlashVars):"","</object>"].join("");else for(l in f=j.createElement("embed"),i)i.hasOwnProperty(l)&&
f.setAttribute(l,i[l]);xa();m=O();if(i=fa())if(c.oMC=A(c.movieID)||j.createElement("div"),c.oMC.id)p=c.oMC.className,c.oMC.className=(p?p+" ":"movieContainer")+(m?" "+m:""),c.oMC.appendChild(f),F&&(l=c.oMC.appendChild(j.createElement("div")),l.className="sm2-object-box",l.innerHTML=r),T=!0;else{c.oMC.id=c.movieID;c.oMC.className="movieContainer "+m;l=m=null;c.useFlashBlock||(c.useHighPerformance?m={position:"fixed",width:"8px",height:"8px",bottom:"0px",left:"0px",overflow:"hidden"}:(m={position:"absolute",
width:"6px",height:"6px",top:"-9999px",left:"-9999px"},k&&(m.left=Math.abs(parseInt(m.left,10))+"px")));mb&&(c.oMC.style.zIndex=1E4);if(!c.debugFlash)for(p in m)m.hasOwnProperty(p)&&(c.oMC.style[p]=m[p]);try{F||c.oMC.appendChild(f),i.appendChild(c.oMC),F&&(l=c.oMC.appendChild(j.createElement("div")),l.className="sm2-object-box",l.innerHTML=r),T=!0}catch(s){throw Error(q("domError")+" \n"+s.toString());}}S=!0;e();c._wD("soundManager::createMovie(): Trying to load "+d+(!Q&&c.altURL?" (alternate URL)":
""),1);return!0};ea=function(){if(c.html5Only)return ga(),!1;if(h)return!1;if(!c.url)return n("noURL"),!1;h=c.getMovie(c.id);h||(W?(F?c.oMC.innerHTML=ya:c.oMC.appendChild(W),W=null,S=!0):ga(c.id,c.url),h=c.getMovie(c.id));h&&n("waitEI");"function"===typeof c.oninitmovie&&setTimeout(c.oninitmovie,1);return!0};L=function(){setTimeout(Oa,1E3)};Oa=function(){var a,d=!1;if(!c.url||X)return!1;X=!0;s.remove(i,"load",L);if(na&&!Ja)return n("waitFocus"),!1;p||(a=c.getMoviePercent(),c._wD(q("waitImpatient",
0<a?" (SWF "+a+"% loaded)":"")),0<a&&100>a&&(d=!0));setTimeout(function(){a=c.getMoviePercent();if(d)return X=!1,c._wD(q("waitSWF")),i.setTimeout(L,1),!1;p||(c._wD("soundManager: No Flash response within expected time.\nLikely causes: "+(0===a?"Loading "+c.movieURL+" may have failed (and/or Flash "+k+"+ not present?), ":"")+"Flash blocked or JS-Flash security error."+(c.debugFlash?" "+q("checkSWF"):""),2),!Q&&a&&(n("localFail",2),c.debugFlash||n("tryDebug",2)),0===a&&c._wD(q("swf404",c.url)),y("flashtojs",
!1,": Timed out"+Q?" (Check flash security or flash blockers)":" (No plugin/missing SWF?)"));!p&&cb&&(null===a?c.useFlashBlock||0===c.flashLoadTimeout?(c.useFlashBlock&&za(),n("waitForever")):ha(!0):0===c.flashLoadTimeout?n("waitForever"):ha(!0))},c.flashLoadTimeout)};ca=function(){if(Ja||!na)return s.remove(i,"focus",ca),!0;Ja=cb=!0;n("gotFocus");X=!1;L();s.remove(i,"focus",ca);return!0};ab=function(){var a,d=[];if(c.useHTML5Audio&&c.hasHTML5){for(a in c.audioFormats)c.audioFormats.hasOwnProperty(a)&&
d.push(a+": "+c.html5[a]+(!c.html5[a]&&u&&c.flash[a]?" (using flash)":c.preferFlash&&c.flash[a]&&u?" (preferring flash)":!c.html5[a]?" ("+(c.audioFormats[a].required?"required, ":"")+"and no flash support)":""));c._wD("-- SoundManager 2: HTML5 support tests ("+c.html5Test+"): "+d.join(", ")+" --",1)}};U=function(a){if(p)return!1;if(c.html5Only)return c._wD("-- SoundManager 2: loaded --"),p=!0,K(),y("onload",!0),!0;var d=!0,e;if(!c.useFlashBlock||!c.flashLoadTimeout||c.getMoviePercent())p=!0,w&&(e=
{type:!u&&B?"NO_FLASH":"INIT_TIMEOUT"});c._wD("-- SoundManager 2 "+(w?"failed to load":"loaded")+" ("+(w?"Flash security/load error":"OK")+") --",1);w||a?(c.useFlashBlock&&c.oMC&&(c.oMC.className=O()+" "+(null===c.getMoviePercent()?"swf_timedout":"swf_error")),J({type:"ontimeout",error:e,ignoreInit:!0}),y("onload",!1),N(e),d=!1):y("onload",!0);w||(c.waitForWindowLoad&&!ba?(n("waitOnload"),s.add(i,"load",K)):(c.waitForWindowLoad&&ba&&n("docLoaded"),K()));return d};Na=function(){var a,d=c.setupOptions;
for(a in d)d.hasOwnProperty(a)&&(c[a]===g?c[a]=d[a]:c[a]!==d[a]&&(c.setupOptions[a]=c[a]))};ra=function(){n("init");if(p)return n("didInit"),!1;if(c.html5Only)return p||(s.remove(i,"load",c.beginDelayedInit),c.enabled=!0,U()),!0;ea();try{n("flashJS"),h._externalInterfaceTest(!1),Pa(!0,c.flashPollingInterval||(c.useHighPerformance?10:50)),c.debugMode||h._disableDebug(),c.enabled=!0,y("jstoflash",!0),c.html5Only||s.add(i,"unload",qa)}catch(a){return c._wD("js/flash exception: "+a.toString()),y("jstoflash",
!1),N({type:"JS_TO_FLASH_EXCEPTION",fatal:!0}),ha(!0),U(),!1}U();s.remove(i,"load",c.beginDelayedInit);return!0};M=function(){if(V)return!1;V=!0;Na();xa();var a=null,a=null,d=G.console!==g&&"function"===typeof console.log,e=R.toLowerCase();-1!==e.indexOf("sm2-usehtml5audio=")&&(a="1"===e.charAt(e.indexOf("sm2-usehtml5audio=")+18),d&&console.log((a?"Enabling ":"Disabling ")+"useHTML5Audio via URL parameter"),c.setup({useHTML5Audio:a}));-1!==e.indexOf("sm2-preferflash=")&&(a="1"===e.charAt(e.indexOf("sm2-preferflash=")+
16),d&&console.log((a?"Enabling ":"Disabling ")+"preferFlash via URL parameter"),c.setup({preferFlash:a}));!u&&c.hasHTML5&&(c._wD("SoundManager: No Flash detected"+(!c.useHTML5Audio?", enabling HTML5.":". Trying HTML5-only mode.")),c.setup({useHTML5Audio:!0,preferFlash:!1}));Xa();c.html5.usingFlash=Wa();B=c.html5.usingFlash;ab();!u&&B&&(n("needFlash"),c.setup({flashLoadTimeout:1}));j.removeEventListener&&j.removeEventListener("DOMContentLoaded",M,!1);ea();return!0};Ca=function(){"complete"===j.readyState&&
(M(),j.detachEvent("onreadystatechange",Ca));return!0};wa=function(){ba=!0;s.remove(i,"load",wa)};Da();s.add(i,"focus",ca);s.add(i,"load",L);s.add(i,"load",wa);j.addEventListener?j.addEventListener("DOMContentLoaded",M,!1):j.attachEvent?j.attachEvent("onreadystatechange",Ca):(y("onload",!1),N({type:"NO_DOM2_EVENTS",fatal:!0}))}var pa=null;if(G.SM2_DEFER===g||!SM2_DEFER)pa=new $;G.SoundManager=$;G.soundManager=pa})(window);