/** @license


 SoundManager 2: JavaScript Sound for the Web
 ----------------------------------------------
 http://schillmania.com/projects/soundmanager2/

 Copyright (c) 2007, Scott Schiller. All rights reserved.
 Code provided under the BSD License:
 http://schillmania.com/projects/soundmanager2/license.txt

 V2.97a.20111030+DEV
*/
(function(D){function U(U,ha){function n(c){return function(a){return!this._t||!this._t._a?(this._t&&this._t.sID?b._wD(l+"ignoring "+a.type+": "+this._t.sID):b._wD(l+"ignoring "+a.type),null):c.call(this,a)}}this.flashVersion=8;this.debugMode=true;this.debugFlash=false;this.useConsole=true;this.waitForWindowLoad=this.consoleOnly=false;this.bgColor="#ffffff";this.useHighPerformance=false;this.html5PollingInterval=this.flashPollingInterval=null;this.flashLoadTimeout=1E3;this.wmode=null;this.allowScriptAccess=
"always";this.useFlashBlock=false;this.useHTML5Audio=true;this.html5Test=/^(probably|maybe)$/i;this.preferFlash=true;this.noSWFCache=false;this.html5PollingInterval=50;this.audioFormats={mp3:{type:['audio/mpeg; codecs="mp3"',"audio/mpeg","audio/mp3","audio/MPA","audio/mpa-robust"],required:true},mp4:{related:["aac","m4a"],type:['audio/mp4; codecs="mp4a.40.2"',"audio/aac","audio/x-m4a","audio/MP4A-LATM","audio/mpeg4-generic"],required:false},ogg:{type:["audio/ogg; codecs=vorbis"],required:false},wav:{type:['audio/wav; codecs="1"',
"audio/wav","audio/wave","audio/x-wav"],required:false}};this.defaultOptions={autoLoad:false,stream:true,autoPlay:false,loops:1,onid3:null,onload:null,whileloading:null,onplay:null,onpause:null,onresume:null,whileplaying:null,onposition:null,onstop:null,onfailure:null,onfinish:null,multiShot:true,multiShotEvents:false,position:null,pan:0,type:null,usePolicyFile:false,volume:100};this.flash9Options={isMovieStar:null,usePeakData:false,useWaveformData:false,useEQData:false,onbufferchange:null,ondataerror:null};
this.movieStarOptions={bufferTime:3,serverURL:null,onconnect:null,duration:null};this.movieID="sm2-container";this.id=ha||"sm2movie";this.swfCSS={swfBox:"sm2-object-box",swfDefault:"movieContainer",swfError:"swf_error",swfTimedout:"swf_timedout",swfLoaded:"swf_loaded",swfUnblocked:"swf_unblocked",sm2Debug:"sm2_debug",highPerf:"high_performance",flashDebug:"flash_debug"};this.debugID="soundmanager-debug";this.debugURLParam=/([#?&])debug=1/i;this.versionNumber="V2.97a.20111030+DEV";this.movieURL=this.version=
null;this.url=U||null;this.altURL=null;this.enabled=this.swfLoaded=false;this.oMC=this.o=null;this.sounds={};this.soundIDs=[];this.didFlashBlock=this.specialWmodeCase=this.muted=false;this.filePattern=null;this.filePatterns={flash8:/\.mp3(\?.*)?$/i,flash9:/\.mp3(\?.*)?$/i};this.features={buffering:false,peakData:false,waveformData:false,eqData:false,movieStar:false};this.sandbox={type:null,types:{remote:"remote (domain-based) rules",localWithFile:"local with file access (no internet access)",localWithNetwork:"local with network (internet access only, no local access)",
localTrusted:"local, trusted (local+internet access)"},description:null,noRemote:null,noLocal:null};var ia;try{ia=typeof Audio!=="undefined"&&typeof(new Audio).canPlayType!=="undefined"}catch(cb){ia=false}this.hasHTML5=ia;this.html5={usingFlash:null};this.flash={};this.ignoreFlash=this.html5Only=false;var Ca,b=this,l="HTML5::",v,r=navigator.userAgent,k=D,L=k.location.href.toString(),g=document,ja,V,h,z=[],ka=true,t,M=false,N=false,o=false,w=false,la=false,m,Wa=0,O,s,ma,E,F,W,Da,na,C,X,Y,G,oa,Z,$,
H,Ea,pa,Xa=["log","info","warn","error"],Fa,aa,Ga,P=null,qa=null,p,ra,I,Ha,ba,ca,sa,j,da=false,ta=false,Ia,Ja,Ka,ea=0,Q=null,x=null,La,fa,R,A,ua,va,Ma,q,Na=Array.prototype.slice,S=false,u,ga,Oa,y,Pa,wa=r.match(/(ipad|iphone|ipod)/i),Ya=r.match(/firefox/i),Za=r.match(/droid/i),B=r.match(/msie/i),$a=r.match(/webkit/i),T=r.match(/safari/i)&&!r.match(/chrome/i),ab=r.match(/opera/i),xa=r.match(/(mobile|pre\/|xoom)/i)||wa,ya=!L.match(/usehtml5audio/i)&&!L.match(/sm2\-ignorebadua/i)&&T&&r.match(/OS X 10_6_([3-7])/i),
za=typeof console!=="undefined"&&typeof console.log!=="undefined",Aa=typeof g.hasFocus!=="undefined"?g.hasFocus():null,J=T&&typeof g.hasFocus==="undefined",Qa=!J,Ra=/(mp3|mp4|mpa)/i,K=g.location?g.location.protocol.match(/http/i):null,Sa=!K?"http://":"",Ta=/^\s*audio\/(?:x-)?(?:mpeg4|aac|flv|mov|mp4||m4v|m4a|mp4v|3gp|3g2)\s*(?:$|;)/i,Ua="mpeg4,aac,flv,mov,mp4,m4v,f4v,m4a,mp4v,3gp,3g2".split(","),bb=RegExp("\\.("+Ua.join("|")+")(\\?.*)?$","i");this.mimePattern=/^\s*audio\/(?:x-)?(?:mp(?:eg|3))\s*(?:$|;)/i;
this.useAltURL=!K;this._global_a=null;if(xa&&(b.useHTML5Audio=true,b.preferFlash=false,wa))S=b.ignoreFlash=true;this.supported=this.ok=function(){return x?o&&!w:b.useHTML5Audio&&b.hasHTML5};this.getMovie=function(b){return v(b)||g[b]||k[b]};this.createSound=function(c){function a(){e=ba(e);b.sounds[d.id]=new Ca(d);b.soundIDs.push(d.id);return b.sounds[d.id]}var e=null,f=null,d=null;if(!o||!b.ok())return sa("soundManager.createSound(): "+p(!o?"notReady":"notOK")),false;arguments.length===2&&(c={id:arguments[0],
url:arguments[1]});d=e=s(c);d.id.toString().charAt(0).match(/^[0-9]$/)&&b._wD("soundManager.createSound(): "+p("badID",d.id),2);b._wD("soundManager.createSound(): "+d.id+" ("+d.url+")",1);if(j(d.id,true))return b._wD("soundManager.createSound(): "+d.id+" exists",1),b.sounds[d.id];if(fa(d))f=a(),b._wD("Loading sound "+d.id+" via HTML5"),f._setup_html5(d);else{if(h>8){if(d.isMovieStar===null)d.isMovieStar=d.serverURL||(d.type?d.type.match(Ta):false)||d.url.match(bb);d.isMovieStar&&b._wD("soundManager.createSound(): using MovieStar handling");
if(d.isMovieStar){if(d.usePeakData)m("noPeak"),d.usePeakData=false;d.loops>1&&m("noNSLoop")}}d=ca(d,"soundManager.createSound(): ");f=a();if(h===8)b.o._createSound(d.id,d.loops||1,d.usePolicyFile);else if(b.o._createSound(d.id,d.url,d.usePeakData,d.useWaveformData,d.useEQData,d.isMovieStar,d.isMovieStar?d.bufferTime:false,d.loops||1,d.serverURL,d.duration||null,d.autoPlay,true,d.autoLoad,d.usePolicyFile),!d.serverURL)f.connected=true,d.onconnect&&d.onconnect.apply(f);!d.serverURL&&(d.autoLoad||d.autoPlay)&&
f.load(d)}!d.serverURL&&d.autoPlay&&f.play();return f};this.destroySound=function(c,a){if(!j(c))return false;var e=b.sounds[c],f;e._iO={};e.stop();e.unload();for(f=0;f<b.soundIDs.length;f++)if(b.soundIDs[f]===c){b.soundIDs.splice(f,1);break}a||e.destruct(true);delete b.sounds[c];return true};this.load=function(c,a){return!j(c)?false:b.sounds[c].load(a)};this.unload=function(c){return!j(c)?false:b.sounds[c].unload()};this.onposition=this.onPosition=function(c,a,e,f){return!j(c)?false:b.sounds[c].onposition(a,
e,f)};this.clearOnPosition=function(c,a,e){return!j(c)?false:b.sounds[c].clearOnPosition(a,e)};this.start=this.play=function(c,a){if(!o||!b.ok())return sa("soundManager.play(): "+p(!o?"notReady":"notOK")),false;return!j(c)?(a instanceof Object||(a={url:a}),a&&a.url?(b._wD('soundManager.play(): attempting to create "'+c+'"',1),a.id=c,b.createSound(a).play()):false):b.sounds[c].play(a)};this.setPosition=function(c,a){return!j(c)?false:b.sounds[c].setPosition(a)};this.stop=function(c){if(!j(c))return false;
b._wD("soundManager.stop("+c+")",1);return b.sounds[c].stop()};this.stopAll=function(){var c;b._wD("soundManager.stopAll()",1);for(c in b.sounds)b.sounds.hasOwnProperty(c)&&b.sounds[c].stop()};this.pause=function(c){return!j(c)?false:b.sounds[c].pause()};this.pauseAll=function(){var c;for(c=b.soundIDs.length;c--;)b.sounds[b.soundIDs[c]].pause()};this.resume=function(c){return!j(c)?false:b.sounds[c].resume()};this.resumeAll=function(){var c;for(c=b.soundIDs.length;c--;)b.sounds[b.soundIDs[c]].resume()};
this.togglePause=function(c){return!j(c)?false:b.sounds[c].togglePause()};this.setPan=function(c,a){return!j(c)?false:b.sounds[c].setPan(a)};this.setVolume=function(c,a){return!j(c)?false:b.sounds[c].setVolume(a)};this.mute=function(c){var a=0;typeof c!=="string"&&(c=null);if(c){if(!j(c))return false;b._wD('soundManager.mute(): Muting "'+c+'"');return b.sounds[c].mute()}else{b._wD("soundManager.mute(): Muting all sounds");for(a=b.soundIDs.length;a--;)b.sounds[b.soundIDs[a]].mute();b.muted=true}return true};
this.muteAll=function(){b.mute()};this.unmute=function(c){typeof c!=="string"&&(c=null);if(c){if(!j(c))return false;b._wD('soundManager.unmute(): Unmuting "'+c+'"');return b.sounds[c].unmute()}else{b._wD("soundManager.unmute(): Unmuting all sounds");for(c=b.soundIDs.length;c--;)b.sounds[b.soundIDs[c]].unmute();b.muted=false}return true};this.unmuteAll=function(){b.unmute()};this.toggleMute=function(c){return!j(c)?false:b.sounds[c].toggleMute()};this.getMemoryUse=function(){var c=0;b.o&&h!==8&&(c=
parseInt(b.o._getMemoryUse(),10));return c};this.disable=function(c){var a;typeof c==="undefined"&&(c=false);if(w)return false;w=true;m("shutdown",1);for(a=b.soundIDs.length;a--;)Fa(b.sounds[b.soundIDs[a]]);O(c);q.remove(k,"load",F);return true};this.canPlayMIME=function(c){var a;b.hasHTML5&&(a=R({type:c}));return!x||a?a:c?!!(h>8&&c.match(Ta)||c.match(b.mimePattern)):null};this.canPlayURL=function(c){var a;b.hasHTML5&&(a=R({url:c}));return!x||a?a:c?!!c.match(b.filePattern):null};this.canPlayLink=
function(c){return typeof c.type!=="undefined"&&c.type&&b.canPlayMIME(c.type)?true:b.canPlayURL(c.href)};this.getSoundById=function(c,a){if(!c)throw Error("soundManager.getSoundById(): sID is null/undefined");var e=b.sounds[c];!e&&!a&&b._wD('"'+c+'" is an invalid sound ID.',2);return e};this.onready=function(c,a){if(c&&c instanceof Function)return o&&b._wD(p("queue","onready")),a||(a=k),ma("onready",c,a),E(),true;else throw p("needFunction","onready");};this.ontimeout=function(c,a){if(c&&c instanceof
Function)return o&&b._wD(p("queue","ontimeout")),a||(a=k),ma("ontimeout",c,a),E({type:"ontimeout"}),true;else throw p("needFunction","ontimeout");};this._wD=this._writeDebug=function(c,a,e){var f,d;if(!b.debugMode)return false;typeof e!=="undefined"&&e&&(c=c+" | "+(new Date).getTime());if(za&&b.useConsole){e=Xa[a];if(typeof console[e]!=="undefined")console[e](c);else console.log(c);if(b.useConsoleOnly)return true}try{f=v("soundmanager-debug");if(!f)return false;d=g.createElement("div");if(++Wa%2===
0)d.className="sm2-alt";a=typeof a==="undefined"?0:parseInt(a,10);d.appendChild(g.createTextNode(c));if(a){if(a>=2)d.style.fontWeight="bold";if(a===3)d.style.color="#ff3333"}f.insertBefore(d,f.firstChild)}catch(Ba){}return true};this._debug=function(){var c,a;m("currentObj",1);for(c=0,a=b.soundIDs.length;c<a;c++)b.sounds[b.soundIDs[c]]._debug()};this.reboot=function(){b._wD("soundManager.reboot()");b.soundIDs.length&&b._wD("Destroying "+b.soundIDs.length+" SMSound objects...");var c,a;for(c=b.soundIDs.length;c--;)b.sounds[b.soundIDs[c]].destruct();
try{if(B)qa=b.o.innerHTML;P=b.o.parentNode.removeChild(b.o);b._wD("Flash movie removed.")}catch(e){m("badRemove",2)}qa=P=x=null;b.enabled=oa=o=da=ta=M=N=w=b.swfLoaded=false;b.soundIDs=b.sounds=[];b.o=null;for(c in z)if(z.hasOwnProperty(c))for(a=z[c].length;a--;)z[c][a].fired=false;b._wD("soundManager: Rebooting...");k.setTimeout(b.beginDelayedInit,20)};this.getMoviePercent=function(){return b.o&&typeof b.o.PercentLoaded!=="undefined"?b.o.PercentLoaded():null};this.beginDelayedInit=function(){la=true;
G();setTimeout(function(){if(ta)return false;$();Y();return ta=true},20);W()};this.destruct=function(){b._wD("soundManager.destruct()");b.disable(true)};Ca=function(c){var a=this,e,f,d,Ba,i,g,k=null,Va=null;this.sID=c.id;this.url=c.url;this._iO=this.instanceOptions=this.options=s(c);this.pan=this.options.pan;this.volume=this.options.volume;this._lastURL=null;this.isHTML5=false;this._a=null;this.id3={};this._debug=function(){if(b.debugMode){var c=null,d=[],e,f;for(c in a.options)a.options[c]!==null&&
(a.options[c]instanceof Function?(e=a.options[c].toString(),e=e.replace(/\s\s+/g," "),f=e.indexOf("{"),d.push(" "+c+": {"+e.substr(f+1,Math.min(Math.max(e.indexOf("\n")-1,64),64)).replace(/\n/g,"")+"... }")):d.push(" "+c+": "+a.options[c]));b._wD("SMSound() merged options: {\n"+d.join(", \n")+"\n}")}};this._debug();this.load=function(c){var d=null;if(typeof c!=="undefined")a._iO=s(c,a.options),a.instanceOptions=a._iO;else if(c=a.options,a._iO=c,a.instanceOptions=a._iO,a._lastURL&&a._lastURL!==a.url)m("manURL"),
a._iO.url=a.url,a.url=null;if(!a._iO.url)a._iO.url=a.url;b._wD("SMSound.load(): "+a._iO.url,1);if(a._iO.url===a.url&&a.readyState!==0&&a.readyState!==2)return m("onURL",1),a.readyState===3&&a._iO.onload&&a._iO.onload.apply(a,[!!a.duration]),a;a._lastURL=a.url;a.loaded=false;a.readyState=1;a.playState=0;if(fa(a._iO))d=a._setup_html5(a._iO),d._called_load?b._wD(l+"ignoring request to load again: "+a.sID):(b._wD(l+"load: "+a.sID),a._html5_canplay=false,a._a.autobuffer="auto",a._a.preload="auto",d.load(),
d._called_load=true,a._iO.autoPlay&&a.play());else try{a.isHTML5=false,a._iO=ca(ba(a._iO)),h===8?b.o._load(a.sID,a._iO.url,a._iO.stream,a._iO.autoPlay,a._iO.whileloading?1:0,a._iO.loops||1,a._iO.usePolicyFile):b.o._load(a.sID,a._iO.url,!!a._iO.stream,!!a._iO.autoPlay,a._iO.loops||1,!!a._iO.autoLoad,a._iO.usePolicyFile)}catch(e){m("smError",2),t("onload",false),H({type:"SMSOUND_LOAD_JS_EXCEPTION",fatal:true})}return a};this.unload=function(){a.readyState!==0&&(b._wD('SMSound.unload(): "'+a.sID+'"'),
a.isHTML5?(f(),a._a&&(a._a.pause(),ua(a._a))):h===8?b.o._unload(a.sID,"about:blank"):b.o._unload(a.sID),e());return a};this.destruct=function(c){b._wD('SMSound.destruct(): "'+a.sID+'"');if(a.isHTML5){if(f(),a._a)a._a.pause(),ua(a._a),S||a._remove_html5_events(),a._a._t=null,a._a=null}else a._iO.onfailure=null,b.o._destroySound(a.sID);c||b.destroySound(a.sID,true)};this.start=this.play=function(c,e){var f,e=e===void 0?true:e;c||(c={});a._iO=s(c,a._iO);a._iO=s(a._iO,a.options);a.instanceOptions=a._iO;
if(a._iO.serverURL&&!a.connected)return a.getAutoPlay()||(b._wD("SMSound.play():  Netstream not connected yet - setting autoPlay"),a.setAutoPlay(true)),a;fa(a._iO)&&(a._setup_html5(a._iO),d());if(a.playState===1&&!a.paused)if(f=a._iO.multiShot)b._wD('SMSound.play(): "'+a.sID+'" already playing (multi-shot)',1);else return b._wD('SMSound.play(): "'+a.sID+'" already playing (one-shot)',1),a;if(a.loaded)b._wD('SMSound.play(): "'+a.sID+'"');else if(a.readyState===0){b._wD('SMSound.play(): Attempting to load "'+
a.sID+'"',1);if(!a.isHTML5)a._iO.autoPlay=true;a.load(a._iO)}else if(a.readyState===2)return b._wD('SMSound.play(): Could not load "'+a.sID+'" - exiting',2),a;else b._wD('SMSound.play(): "'+a.sID+'" is loading - attempting to play..',1);if(!a.isHTML5&&h===9&&a.position>0&&a.position===a.duration)b._wD('SMSound.play(): "'+a.sID+'": Sound at end, resetting to position:0'),a._iO.position=0;if(a.paused&&a.position&&a.position>0)b._wD('SMSound.play(): "'+a.sID+'" is resuming from paused state',1),a.resume();
else{f=function(){a._iO=s(c,a._iO);a.play(a._iO)};if(a.instanceCount===0&&a.playState===0&&!isNaN(a._iO.from)&&!isNaN(a._iO.to)){if(a.isHTML5&&!a._html5_canplay)return b._wD('SMSound.play(): Beginning load of "'+a.sID+'" for from/to case'),a.load({_oncanplay:f}),false;else if(!a.isHTML5&&!a.loaded&&(!a.readyState||a.readyState!==2))return b._wD('SMSound.play(): Preloading "'+a.sID+'" for from/to case'),a.load({onload:f}),false;a._iO=s(c,a._iO);a._iO=g()}b._wD('SMSound.play(): "'+a.sID+'" is starting to play');
(!a.instanceCount||a._iO.multiShotEvents||!a.isHTML5&&h>8&&!a.getAutoPlay())&&a.instanceCount++;a.playState===0&&a._iO.onposition&&Ba(a);a.playState=1;a.paused=false;a.position=typeof a._iO.position!=="undefined"&&!isNaN(a._iO.position)?a._iO.position:0;if(!a.isHTML5)a._iO=ca(ba(a._iO));if(a._iO.onplay&&e)a._iO.onplay.apply(a),a._onplay_called=true;a.setVolume(a._iO.volume,true);a.setPan(a._iO.pan,true);a.isHTML5?(d(),f=a._setup_html5(),a.setPosition(a._iO.position),f.play()):b.o._start(a.sID,a._iO.loops||
1,h===9?a._iO.position:a._iO.position/1E3)}return a};this.stop=function(c){if(a.playState===1){a._onbufferchange(0);a._resetOnPosition(0);a.paused=false;if(!a.isHTML5)a.playState=0;i(a);a._iO.onstop&&a._iO.onstop.apply(a);if(a.isHTML5){if(a._a)a.setPosition(0),a._a.pause(),a.playState=0,a._onTimer(),f()}else b.o._stop(a.sID,c),a._iO.serverURL&&a.unload();a.instanceCount=0;a._iO={}}return a};this.setAutoPlay=function(c){b._wD("sound "+a.sID+" turned autoplay "+(c?"on":"off"));a._iO.autoPlay=c;a.isHTML5||
(b.o._setAutoPlay(a.sID,c),c&&!a.instanceCount&&a.readyState===1&&(a.instanceCount++,b._wD("sound "+a.sID+" incremented instance count to "+a.instanceCount)))};this.getAutoPlay=function(){return a._iO.autoPlay};this.setPosition=function(c){c===void 0&&(c=0);var d=a.isHTML5?Math.max(c,0):Math.min(a.duration||a._iO.duration,Math.max(c,0));a.position=d;c=a.position/1E3;a._resetOnPosition(a.position);a._iO.position=d;if(a.isHTML5){if(a._a)if(a._html5_canplay){if(a._a.currentTime!==c){b._wD("setPosition("+
c+"): setting position");try{a._a.currentTime=c,(a.playState===0||a.paused)&&a._a.pause()}catch(e){b._wD("setPosition("+c+"): setting position failed: "+e.message,2)}}}else b._wD("setPosition("+c+"): delaying, sound not ready")}else c=h===9?a.position:c,a.readyState&&a.readyState!==2&&b.o._setPosition(a.sID,c,a.paused||!a.playState);a.isHTML5&&a.paused&&a._onTimer(true);return a};this.pause=function(c){if(a.paused||a.playState===0&&a.readyState!==1)return a;b._wD("SMSound.pause()");a.paused=true;
a.isHTML5?(a._setup_html5().pause(),f()):(c||c===void 0)&&b.o._pause(a.sID);a._iO.onpause&&a._iO.onpause.apply(a);return a};this.resume=function(){if(!a.paused)return a;b._wD("SMSound.resume()");a.paused=false;a.playState=1;a.isHTML5?(a._setup_html5().play(),d()):(a._iO.isMovieStar&&a.setPosition(a.position),b.o._pause(a.sID));!a._onplay_called&&a._iO.onplay?(a._iO.onplay.apply(a),a._onplay_called=true):a._iO.onresume&&a._iO.onresume.apply(a);return a};this.togglePause=function(){b._wD("SMSound.togglePause()");
if(a.playState===0)return a.play({position:h===9&&!a.isHTML5?a.position:a.position/1E3}),a;a.paused?a.resume():a.pause();return a};this.setPan=function(c,d){typeof c==="undefined"&&(c=0);typeof d==="undefined"&&(d=false);a.isHTML5||b.o._setPan(a.sID,c);a._iO.pan=c;if(!d)a.pan=c,a.options.pan=c;return a};this.setVolume=function(c,d){typeof c==="undefined"&&(c=100);typeof d==="undefined"&&(d=false);if(a.isHTML5){if(a._a)a._a.volume=Math.max(0,Math.min(1,c/100))}else b.o._setVolume(a.sID,b.muted&&!a.muted||
a.muted?0:c);a._iO.volume=c;if(!d)a.volume=c,a.options.volume=c;return a};this.mute=function(){a.muted=true;if(a.isHTML5){if(a._a)a._a.muted=true}else b.o._setVolume(a.sID,0);return a};this.unmute=function(){a.muted=false;var c=typeof a._iO.volume!=="undefined";if(a.isHTML5){if(a._a)a._a.muted=false}else b.o._setVolume(a.sID,c?a._iO.volume:a.options.volume);return a};this.toggleMute=function(){return a.muted?a.unmute():a.mute()};this.onposition=this.onPosition=function(b,c,d){a._onPositionItems.push({position:b,
method:c,scope:typeof d!=="undefined"?d:a,fired:false});return a};this.clearOnPosition=function(b,c){var d,b=parseInt(b,10);if(isNaN(b))return false;for(d=0;d<a._onPositionItems.length;d++)if(b===a._onPositionItems[d].position&&(!c||c===a._onPositionItems[d].method))a._onPositionItems[d].fired&&a._onPositionFired--,a._onPositionItems.splice(d,1)};this._processOnPosition=function(){var b,c;b=a._onPositionItems.length;if(!b||!a.playState||a._onPositionFired>=b)return false;for(;b--;)if(c=a._onPositionItems[b],
!c.fired&&a.position>=c.position)c.fired=true,a._onPositionFired++,c.method.apply(c.scope,[c.position]);return true};this._resetOnPosition=function(b){var c,d;c=a._onPositionItems.length;if(!c)return false;for(;c--;)if(d=a._onPositionItems[c],d.fired&&b<=d.position)d.fired=false,a._onPositionFired--;return true};g=function(){var c=a._iO.from,d=a._iO.to,e=a._iO,f,i;i=function(){b._wD(a.sID+': "to" time of '+d+" reached.");a.clearOnPosition(d,i);a.stop()};f=function(){b._wD(a.sID+': playing "from" '+
c);a.onPosition(d,i)};if(!isNaN(c))e.position=c,e.multiShot=false,f();return e};Ba=function(){var b=a._iO.onposition;if(b)for(var c in b)if(b.hasOwnProperty(c))a.onPosition(parseInt(c,10),b[c])};i=function(){var b=a._iO.onposition;if(b)for(var c in b)b.hasOwnProperty(c)&&a.clearOnPosition(parseInt(c,10))};d=function(){a.isHTML5&&Ia(a)};f=function(){a.isHTML5&&Ja(a)};e=function(){a._onPositionItems=[];a._onPositionFired=0;a._hasTimer=null;a._onplay_called=false;a._a=null;a._html5_canplay=false;a.bytesLoaded=
null;a.bytesTotal=null;a.position=null;a.duration=a._iO&&a._iO.duration?a._iO.duration:null;a.durationEstimate=null;a.failures=0;a.loaded=false;a.playState=0;a.paused=false;a.readyState=0;a.muted=false;a.isBuffering=false;a.instanceOptions={};a.instanceCount=0;a.peakData={left:0,right:0};a.waveformData={left:[],right:[]};a.eqData=[];a.eqData.left=[];a.eqData.right=[]};e();this._onTimer=function(b){var c,d=false,e={};if(a._hasTimer||b)if(a._a&&(b||(a.playState>0||a.readyState===1)&&!a.paused)){c=a._get_html5_duration();
if(c!==k)k=c,a.duration=c,d=true;a.durationEstimate=a.duration;c=a._a.currentTime*1E3||0;c!==Va&&(Va=c,d=true);(d||b)&&a._whileplaying(c,e,e,e,e);return d}else return false};this._get_html5_duration=function(){var b=a._a?a._a.duration*1E3:a._iO?a._iO.duration:void 0;return b&&!isNaN(b)&&b!==Infinity?b:a._iO?a._iO.duration:null};this._setup_html5=function(c){var c=s(a._iO,c),d=S?b._global_a:a._a,f=decodeURI(c.url),i=d&&d._t?d._t.instanceOptions:null;if(d){if(d._t&&i.url===c.url&&(!a._lastURL||a._lastURL===
i.url))return d;b._wD("setting new URL on existing object: "+f+(a._lastURL?", old URL: "+a._lastURL:""));S&&d._t&&d._t.playState&&c.url!==i.url&&d._t.stop();e();d.src=c.url;a.url=c.url;a._lastURL=c.url;d._called_load=false}else{b._wD("creating HTML5 Audio() element with URL: "+f);d=new Audio(c.url);d._called_load=false;if(Za)d._called_load=true;if(S)b._global_a=d}a.isHTML5=true;a._a=d;d._t=a;a._add_html5_events();d.loop=c.loops>1?"loop":"";c.autoLoad||c.autoPlay?a.load():(d.autobuffer=false,d.preload=
"none");d.loop=c.loops>1?"loop":"";return d};this._add_html5_events=function(){if(a._a._added_events)return false;var c;b._wD(l+"adding event listeners: "+a.sID);a._a._added_events=true;for(c in y)y.hasOwnProperty(c)&&a._a&&a._a.addEventListener(c,y[c],false);return true};this._remove_html5_events=function(){var c;b._wD(l+"removing event listeners: "+a.sID);a._a._added_events=false;for(c in y)y.hasOwnProperty(c)&&a._a&&a._a.removeEventListener(c,y[c],false)};this._onload=function(c){c=!!c;b._wD('SMSound._onload(): "'+
a.sID+'"'+(c?" loaded.":" failed to load? - "+a.url),c?1:2);!c&&!a.isHTML5&&(b.sandbox.noRemote===true&&b._wD("SMSound._onload(): "+p("noNet"),1),b.sandbox.noLocal===true&&b._wD("SMSound._onload(): "+p("noLocal"),1));a.loaded=c;a.readyState=c?3:2;a._onbufferchange(0);a._iO.onload&&a._iO.onload.apply(a,[c]);return true};this._onbufferchange=function(c){if(a.playState===0)return false;if(c&&a.isBuffering||!c&&!a.isBuffering)return false;a.isBuffering=c===1;a._iO.onbufferchange&&(b._wD("SMSound._onbufferchange(): "+
c),a._iO.onbufferchange.apply(a));return true};this._onsuspend=function(){a._iO.onsuspend&&(b._wD("SMSound._onsuspend()"),a._iO.onsuspend.apply(a));return true};this._onfailure=function(c,d,e){a.failures++;b._wD('SMSound._onfailure(): "'+a.sID+'" count '+a.failures);if(a._iO.onfailure&&a.failures===1)a._iO.onfailure(a,c,d,e);else b._wD("SMSound._onfailure(): ignoring")};this._onfinish=function(){var c=a._iO.onfinish;a._onbufferchange(0);a._resetOnPosition(0);if(a.instanceCount){a.instanceCount--;
if(!a.instanceCount)i(a),a.playState=0,a.paused=false,a.instanceCount=0,a.instanceOptions={},a._iO={},f();if((!a.instanceCount||a._iO.multiShotEvents)&&c)b._wD('SMSound._onfinish(): "'+a.sID+'"'),c.apply(a)}};this._whileloading=function(b,c,d,e){a.bytesLoaded=b;a.bytesTotal=c;a.duration=Math.floor(d);a.bufferLength=e;if(a._iO.isMovieStar)a.durationEstimate=a.duration;else if(a.durationEstimate=a._iO.duration?a.duration>a._iO.duration?a.duration:a._iO.duration:parseInt(a.bytesTotal/a.bytesLoaded*a.duration,
10),a.durationEstimate===void 0)a.durationEstimate=a.duration;a.readyState!==3&&a._iO.whileloading&&a._iO.whileloading.apply(a)};this._whileplaying=function(b,c,d,e,f){if(isNaN(b)||b===null)return false;a.position=b;a._processOnPosition();if(!a.isHTML5&&h>8){if(a._iO.usePeakData&&typeof c!=="undefined"&&c)a.peakData={left:c.leftPeak,right:c.rightPeak};if(a._iO.useWaveformData&&typeof d!=="undefined"&&d)a.waveformData={left:d.split(","),right:e.split(",")};if(a._iO.useEQData&&typeof f!=="undefined"&&
f&&f.leftEQ&&(b=f.leftEQ.split(","),a.eqData=b,a.eqData.left=b,typeof f.rightEQ!=="undefined"&&f.rightEQ))a.eqData.right=f.rightEQ.split(",")}a.playState===1&&(!a.isHTML5&&h===8&&!a.position&&a.isBuffering&&a._onbufferchange(0),a._iO.whileplaying&&a._iO.whileplaying.apply(a));return true};this._onid3=function(c,d){b._wD('SMSound._onid3(): "'+this.sID+'" ID3 data received.');var e=[],f,i;for(f=0,i=c.length;f<i;f++)e[c[f]]=d[f];a.id3=s(a.id3,e);a._iO.onid3&&a._iO.onid3.apply(a)};this._onconnect=function(c){c=
c===1;b._wD('SMSound._onconnect(): "'+a.sID+'"'+(c?" connected.":" failed to connect? - "+a.url),c?1:2);if(a.connected=c)a.failures=0,j(a.sID)&&(a.getAutoPlay()?a.play(void 0,a.getAutoPlay()):a._iO.autoLoad&&a.load()),a._iO.onconnect&&a._iO.onconnect.apply(a,[c])};this._ondataerror=function(c){a.playState>0&&(b._wD("SMSound._ondataerror(): "+c),a._iO.ondataerror&&a._iO.ondataerror.apply(a))}};Z=function(){return g.body||g._docElement||g.getElementsByTagName("div")[0]};v=function(b){return g.getElementById(b)};
s=function(c,a){var e={},f,d;for(f in c)c.hasOwnProperty(f)&&(e[f]=c[f]);f=typeof a==="undefined"?b.defaultOptions:a;for(d in f)f.hasOwnProperty(d)&&typeof e[d]==="undefined"&&(e[d]=f[d]);return e};q=function(){function b(a){var a=Na.call(a),c=a.length;e?(a[1]="on"+a[1],c>3&&a.pop()):c===3&&a.push(false);return a}function a(a,b){var c=a.shift(),g=[f[b]];if(e)c[g](a[0],a[1]);else c[g].apply(c,a)}var e=k.attachEvent,f={add:e?"attachEvent":"addEventListener",remove:e?"detachEvent":"removeEventListener"};
return{add:function(){a(b(arguments),"add")},remove:function(){a(b(arguments),"remove")}}}();y={abort:n(function(){b._wD(l+"abort: "+this._t.sID)}),canplay:n(function(){if(this._t._html5_canplay)return true;this._t._html5_canplay=true;b._wD(l+"canplay: "+this._t.sID+", "+this._t.url);this._t._onbufferchange(0);var c=!isNaN(this._t.position)?this._t.position/1E3:null;if(this._t.position&&this.currentTime!==c){b._wD(l+"canplay: setting position to "+c);try{this.currentTime=c}catch(a){b._wD(l+"setting position failed: "+
a.message,2)}}this._t._iO._oncanplay&&this._t._iO._oncanplay()}),load:n(function(){this._t.loaded||(this._t._onbufferchange(0),this._t._whileloading(this._t.bytesTotal,this._t.bytesTotal,this._t._get_html5_duration()),this._t._onload(true))}),emptied:n(function(){b._wD(l+"emptied: "+this._t.sID)}),ended:n(function(){b._wD(l+"ended: "+this._t.sID);this._t._onfinish()}),error:n(function(){b._wD(l+"error: "+this.error.code);this._t._onload(false)}),loadeddata:n(function(){var c=this._t,a=c.bytesTotal||
1;b._wD(l+"loadeddata: "+this._t.sID);if(!c._loaded&&!T)c.duration=c._get_html5_duration(),c._whileloading(a,a,c._get_html5_duration()),c._onload(true)}),loadedmetadata:n(function(){b._wD(l+"loadedmetadata: "+this._t.sID)}),loadstart:n(function(){b._wD(l+"loadstart: "+this._t.sID);this._t._onbufferchange(1)}),play:n(function(){b._wD(l+"play: "+this._t.sID+", "+this._t.url);this._t._onbufferchange(0)}),playing:n(function(){b._wD(l+"playing: "+this._t.sID);this._t._onbufferchange(0)}),progress:n(function(c){if(this._t.loaded)return false;
var a,e,f;f=0;var d=c.type==="progress";e=c.target.buffered;var g=c.loaded||0,i=c.total||1;if(e&&e.length){for(a=e.length;a--;)f=e.end(a)-e.start(a);g=f/c.target.duration;if(d&&e.length>1){f=[];e=e.length;for(a=0;a<e;a++)f.push(c.target.buffered.start(a)+"-"+c.target.buffered.end(a));b._wD(l+"progress: timeRanges: "+f.join(", "))}d&&!isNaN(g)&&b._wD(l+"progress: "+this._t.sID+": "+Math.floor(g*100)+"% loaded")}isNaN(g)||(this._t._onbufferchange(0),this._t._whileloading(g,i,this._t._get_html5_duration()),
g&&i&&g===i&&y.load.call(this,c))}),ratechange:n(function(){b._wD(l+"ratechange: "+this._t.sID)}),suspend:n(function(c){b._wD(l+"suspend: "+this._t.sID);y.progress.call(this,c);this._t._onsuspend()}),stalled:n(function(){b._wD(l+"stalled: "+this._t.sID)}),timeupdate:n(function(){this._t._onTimer()}),waiting:n(function(){b._wD(l+"waiting: "+this._t.sID);this._t._onbufferchange(1)})};fa=function(c){return!c.serverURL&&(c.type?R({type:c.type}):R({url:c.url})||b.html5Only)};ua=function(b){if(b)b.src=
Ya?"":"about:blank"};R=function(c){function a(a){return b.preferFlash&&u&&!b.ignoreFlash&&typeof b.flash[a]!=="undefined"&&b.flash[a]}if(!b.useHTML5Audio||!b.hasHTML5)return false;var e=c.url||null,c=c.type||null,f=b.audioFormats,d;if(c&&b.html5[c]!=="undefined")return b.html5[c]&&!a(c);if(!A){A=[];for(d in f)f.hasOwnProperty(d)&&(A.push(d),f[d].related&&(A=A.concat(f[d].related)));A=RegExp("\\.("+A.join("|")+")(\\?.*)?$","i")}d=e?e.toLowerCase().match(A):null;if(!d||!d.length)if(c)e=c.indexOf(";"),
d=(e!==-1?c.substr(0,e):c).substr(6);else return false;else d=d[1];return d&&typeof b.html5[d]!=="undefined"?b.html5[d]&&!a(d):(c="audio/"+d,e=b.html5.canPlayType({type:c}),(b.html5[d]=e)&&b.html5[c]&&!a(c))};Ma=function(){function c(c){var d,e,f=false;if(!a||typeof a.canPlayType!=="function")return false;if(c instanceof Array){for(d=0,e=c.length;d<e&&!f;d++)if(b.html5[c[d]]||a.canPlayType(c[d]).match(b.html5Test))f=true,b.html5[c[d]]=true,b.flash[c[d]]=!(!b.preferFlash||!u||!c[d].match(Ra));return f}else return c=
a&&typeof a.canPlayType==="function"?a.canPlayType(c):false,!(!c||!c.match(b.html5Test))}if(!b.useHTML5Audio||typeof Audio==="undefined")return false;var a=typeof Audio!=="undefined"?ab?new Audio(null):new Audio:null,e,f={},d,g;d=b.audioFormats;for(e in d)if(d.hasOwnProperty(e)&&(f[e]=c(d[e].type),f["audio/"+e]=f[e],b.flash[e]=b.preferFlash&&!b.ignoreFlash&&e.match(Ra)?true:false,d[e]&&d[e].related))for(g=d[e].related.length;g--;)f["audio/"+d[e].related[g]]=f[e],b.html5[d[e].related[g]]=f[e],b.flash[d[e].related[g]]=
f[e];f.canPlayType=a?c:null;b.html5=s(b.html5,f);return true};X={notReady:"Not loaded yet - wait for soundManager.onload()/onready()",notOK:"Audio support is not available.",domError:"soundManager::createMovie(): appendChild/innerHTML call failed. DOM not ready or other error.",spcWmode:"soundManager::createMovie(): Removing wmode, preventing known SWF loading issue(s)",swf404:"soundManager: Verify that %s is a valid path.",tryDebug:"Try soundManager.debugFlash = true for more security details (output goes to SWF.)",
checkSWF:"See SWF output for more debug info.",localFail:"soundManager: Non-HTTP page ("+g.location.protocol+" URL?) Review Flash player security settings for this special case:\nhttp://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html\nMay need to add/allow path, eg. c:/sm2/ or /users/me/sm2/",waitFocus:"soundManager: Special case: Waiting for focus-related event..",waitImpatient:"soundManager: Getting impatient, still waiting for Flash%s...",waitForever:"soundManager: Waiting indefinitely for Flash (will recover if unblocked)...",
needFunction:"soundManager: Function object expected for %s",badID:'Warning: Sound ID "%s" should be a string, starting with a non-numeric character',currentObj:"--- soundManager._debug(): Current sound objects ---",waitEI:"soundManager::initMovie(): Waiting for ExternalInterface call from Flash..",waitOnload:"soundManager: Waiting for window.onload()",docLoaded:"soundManager: Document already loaded",onload:"soundManager::initComplete(): calling soundManager.onload()",onloadOK:"soundManager.onload() complete",
init:"soundManager::init()",didInit:"soundManager::init(): Already called?",flashJS:"soundManager: Attempting to call Flash from JS..",secNote:"Flash security note: Network/internet URLs will not load due to security restrictions. Access can be configured via Flash Player Global Security Settings Page: http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html",badRemove:"Warning: Failed to remove flash movie.",noPeak:"Warning: peakData features unsupported for movieStar formats",
shutdown:"soundManager.disable(): Shutting down",queue:"soundManager: Queueing %s handler",smFail:"soundManager: Failed to initialise.",smError:"SMSound.load(): Exception: JS-Flash communication failed, or JS error.",fbTimeout:"No flash response, applying ."+b.swfCSS.swfTimedout+" CSS..",fbLoaded:"Flash loaded",fbHandler:"soundManager::flashBlockHandler()",manURL:"SMSound.load(): Using manually-assigned URL",onURL:"soundManager.load(): current URL already assigned.",badFV:'soundManager.flashVersion must be 8 or 9. "%s" is invalid. Reverting to %s.',
as2loop:"Note: Setting stream:false so looping can work (flash 8 limitation)",noNSLoop:"Note: Looping not implemented for MovieStar formats",needfl9:"Note: Switching to flash 9, required for MP4 formats.",mfTimeout:"Setting flashLoadTimeout = 0 (infinite) for off-screen, mobile flash case",mfOn:"mobileFlash::enabling on-screen flash repositioning",policy:"Enabling usePolicyFile for data access"};p=function(){var b=Na.call(arguments),a=b.shift(),a=X&&X[a]?X[a]:"",e,f;if(a&&b&&b.length)for(e=0,f=b.length;e<
f;e++)a=a.replace("%s",b[e]);return a};ba=function(b){if(h===8&&b.loops>1&&b.stream)m("as2loop"),b.stream=false;return b};ca=function(c,a){if(c&&!c.usePolicyFile&&(c.onid3||c.usePeakData||c.useWaveformData||c.useEQData))b._wD((a||"")+p("policy")),c.usePolicyFile=true;return c};sa=function(c){typeof console!=="undefined"&&typeof console.warn!=="undefined"?console.warn(c):b._wD(c)};ja=function(){return false};Fa=function(b){for(var a in b)b.hasOwnProperty(a)&&typeof b[a]==="function"&&(b[a]=ja)};aa=
function(c){typeof c==="undefined"&&(c=false);if(w||c)m("smFail",2),b.disable(c)};Ga=function(c){var a=null;if(c)if(c.match(/\.swf(\?.*)?$/i)){if(a=c.substr(c.toLowerCase().lastIndexOf(".swf?")+4))return c}else c.lastIndexOf("/")!==c.length-1&&(c+="/");c=(c&&c.lastIndexOf("/")!==-1?c.substr(0,c.lastIndexOf("/")+1):"./")+b.movieURL;b.noSWFCache&&(c+="?ts="+(new Date).getTime());return c};na=function(){h=parseInt(b.flashVersion,10);if(h!==8&&h!==9)b._wD(p("badFV",h,8)),b.flashVersion=h=8;var c=b.debugMode||
b.debugFlash?"_debug.swf":".swf";if(b.useHTML5Audio&&!b.html5Only&&b.audioFormats.mp4.required&&h<9)b._wD(p("needfl9")),b.flashVersion=h=9;b.version=b.versionNumber+(b.html5Only?" (HTML5-only mode)":h===9?" (AS3/Flash 9)":" (AS2/Flash 8)");h>8?(b.defaultOptions=s(b.defaultOptions,b.flash9Options),b.features.buffering=true,b.defaultOptions=s(b.defaultOptions,b.movieStarOptions),b.filePatterns.flash9=RegExp("\\.(mp3|"+Ua.join("|")+")(\\?.*)?$","i"),b.features.movieStar=true):b.features.movieStar=false;
b.filePattern=b.filePatterns[h!==8?"flash9":"flash8"];b.movieURL=(h===8?"soundmanager2.swf":"soundmanager2_flash9.swf").replace(".swf",c);b.features.peakData=b.features.waveformData=b.features.eqData=h>8};Ea=function(c,a){if(!b.o)return false;b.o._setPolling(c,a)};pa=function(){if(b.debugURLParam.test(L))b.debugMode=true;if(v(b.debugID))return false;var c,a,e,f;if(b.debugMode&&!v(b.debugID)&&(!za||!b.useConsole||b.useConsole&&za&&!b.consoleOnly)){c=g.createElement("div");c.id=b.debugID+"-toggle";
a={position:"fixed",bottom:"0px",right:"0px",width:"1.2em",height:"1.2em",lineHeight:"1.2em",margin:"2px",textAlign:"center",border:"1px solid #999",cursor:"pointer",background:"#fff",color:"#333",zIndex:10001};c.appendChild(g.createTextNode("-"));c.onclick=Ha;c.title="Toggle SM2 debug console";if(r.match(/msie 6/i))c.style.position="absolute",c.style.cursor="hand";for(f in a)a.hasOwnProperty(f)&&(c.style[f]=a[f]);a=g.createElement("div");a.id=b.debugID;a.style.display=b.debugMode?"block":"none";
if(b.debugMode&&!v(c.id)){try{e=Z(),e.appendChild(c)}catch(d){throw Error(p("domError")+" \n"+d.toString());}e.appendChild(a)}}};j=this.getSoundById;m=function(c,a){return c?b._wD(p(c),a):""};if(L.indexOf("sm2-debug=alert")+1&&b.debugMode)b._wD=function(b){D.alert(b)};Ha=function(){var c=v(b.debugID),a=v(b.debugID+"-toggle");if(!c)return false;ka?(a.innerHTML="+",c.style.display="none"):(a.innerHTML="-",c.style.display="block");ka=!ka};t=function(b,a,e){if(typeof sm2Debugger!=="undefined")try{sm2Debugger.handleEvent(b,
a,e)}catch(f){}return true};I=function(){var c=[];b.debugMode&&c.push(b.swfCSS.sm2Debug);b.debugFlash&&c.push(b.swfCSS.flashDebug);b.useHighPerformance&&c.push(b.swfCSS.highPerf);return c.join(" ")};ra=function(){var c=p("fbHandler"),a=b.getMoviePercent(),e=b.swfCSS,f={type:"FLASHBLOCK"};if(b.html5Only)return false;if(b.ok()){if(b.didFlashBlock&&b._wD(c+": Unblocked"),b.oMC)b.oMC.className=[I(),e.swfDefault,e.swfLoaded+(b.didFlashBlock?" "+e.swfUnblocked:"")].join(" ")}else{if(x)b.oMC.className=I()+
" "+e.swfDefault+" "+(a===null?e.swfTimedout:e.swfError),b._wD(c+": "+p("fbTimeout")+(a?" ("+p("fbLoaded")+")":""));b.didFlashBlock=true;E({type:"ontimeout",ignoreInit:true,error:f});H(f)}};ma=function(b,a,e){typeof z[b]==="undefined"&&(z[b]=[]);z[b].push({method:a,scope:e||null,fired:false})};E=function(c){c||(c={type:"onready"});if(!o&&c&&!c.ignoreInit)return false;if(c.type==="ontimeout"&&b.ok())return false;var a={success:c&&c.ignoreInit?b.ok():!w},e=c&&c.type?z[c.type]||[]:[],f=[],d,g=[a],i=
x&&b.useFlashBlock&&!b.ok();if(c.error)g[0].error=c.error;for(a=0,d=e.length;a<d;a++)e[a].fired!==true&&f.push(e[a]);if(f.length){b._wD("soundManager: Firing "+f.length+" "+c.type+"() item"+(f.length===1?"":"s"));for(a=0,d=f.length;a<d;a++)if(f[a].scope?f[a].method.apply(f[a].scope,g):f[a].method.apply(this,g),!i)f[a].fired=true}return true};F=function(){k.setTimeout(function(){b.useFlashBlock&&ra();E();b.onload instanceof Function&&(m("onload",1),b.onload.apply(k),m("onloadOK",1));b.waitForWindowLoad&&
q.add(k,"load",F)},1)};ga=function(){if(u!==void 0)return u;var b=false,a=navigator,e=a.plugins,f,d=k.ActiveXObject;if(e&&e.length)(a=a.mimeTypes)&&a["application/x-shockwave-flash"]&&a["application/x-shockwave-flash"].enabledPlugin&&a["application/x-shockwave-flash"].enabledPlugin.description&&(b=true);else if(typeof d!=="undefined"){try{f=new d("ShockwaveFlash.ShockwaveFlash")}catch(g){}b=!!f}return u=b};La=function(){var c,a;if(wa&&r.match(/os (1|2|3_0|3_1)/i)){b.hasHTML5=false;b.html5Only=true;
if(b.oMC)b.oMC.style.display="none";return false}if(b.useHTML5Audio){if(!b.html5||!b.html5.canPlayType)return b._wD("SoundManager: No HTML5 Audio() support detected."),b.hasHTML5=false,true;else b.hasHTML5=true;if(ya&&(b._wD("soundManager::Note: Buggy HTML5 Audio in Safari on this OS X release, see https://bugs.webkit.org/show_bug.cgi?id=32159 - "+(!u?" would use flash fallback for MP3/MP4, but none detected.":"will use flash fallback for MP3/MP4, if available"),1),ga()))return true}else return true;
for(a in b.audioFormats)if(b.audioFormats.hasOwnProperty(a)&&(b.audioFormats[a].required&&!b.html5.canPlayType(b.audioFormats[a].type)||b.flash[a]||b.flash[b.audioFormats[a].type]))c=true;b.ignoreFlash&&(c=false);b.html5Only=b.hasHTML5&&b.useHTML5Audio&&!c;return!b.html5Only};Ia=function(c){if(!c._hasTimer)c._hasTimer=true,!xa&&b.html5PollingInterval&&(Q===null&&ea===0&&(Q=D.setInterval(Ka,b.html5PollingInterval)),ea++)};Ja=function(c){if(c._hasTimer)c._hasTimer=false,!xa&&b.html5PollingInterval&&
ea--};Ka=function(){var c;if(Q!==null&&!ea)return D.clearInterval(Q),Q=null,false;for(c=b.soundIDs.length;c--;)b.sounds[b.soundIDs[c]].isHTML5&&b.sounds[b.soundIDs[c]]._hasTimer&&b.sounds[b.soundIDs[c]]._onTimer()};H=function(c){c=typeof c!=="undefined"?c:{};b.onerror instanceof Function&&b.onerror.apply(k,[{type:typeof c.type!=="undefined"?c.type:null}]);typeof c.fatal!=="undefined"&&c.fatal&&b.disable()};Oa=function(){if(!ya||!ga())return false;var c=b.audioFormats,a,e;for(e in c)if(c.hasOwnProperty(e)&&
(e==="mp3"||e==="mp4"))if(b._wD("soundManager: Using flash fallback for "+e+" format"),b.html5[e]=false,c[e]&&c[e].related)for(a=c[e].related.length;a--;)b.html5[c[e].related[a]]=false};this._setSandboxType=function(c){var a=b.sandbox;a.type=c;a.description=a.types[typeof a.types[c]!=="undefined"?c:"unknown"];b._wD("Flash security sandbox type: "+a.type);if(a.type==="localWithFile")a.noRemote=true,a.noLocal=false,m("secNote",2);else if(a.type==="localWithNetwork")a.noRemote=false,a.noLocal=true;else if(a.type===
"localTrusted")a.noRemote=false,a.noLocal=false};this._externalInterfaceOK=function(c){if(b.swfLoaded)return false;var a=(new Date).getTime();b._wD("soundManager::externalInterfaceOK()"+(c?" (~"+(a-c)+" ms)":""));t("swf",true);t("flashtojs",true);b.swfLoaded=true;J=false;ya&&Oa();B?setTimeout(V,100):V()};$=function(c,a){function e(){b._wD("-- SoundManager 2 "+b.version+(!b.html5Only&&b.useHTML5Audio?b.hasHTML5?" + HTML5 audio":", no HTML5 audio support":"")+(!b.html5Only?(b.useHighPerformance?", high performance mode, ":
", ")+((b.flashPollingInterval?"custom ("+b.flashPollingInterval+"ms)":"normal")+" polling")+(b.wmode?", wmode: "+b.wmode:"")+(b.debugFlash?", flash debug mode":"")+(b.useFlashBlock?", flashBlock mode":""):"")+" --",1)}function f(a,b){return'<param name="'+a+'" value="'+b+'" />'}if(M&&N)return false;if(b.html5Only)return na(),e(),b.oMC=v(b.movieID),V(),N=M=true,false;var d=a||b.url,k=b.altURL||d,i;i=Z();var h,l,j=I(),n,o=null,o=(o=g.getElementsByTagName("html")[0])&&o.dir&&o.dir.match(/rtl/i),c=typeof c===
"undefined"?b.id:c;na();b.url=Ga(K?d:k);a=b.url;b.wmode=!b.wmode&&b.useHighPerformance?"transparent":b.wmode;if(b.wmode!==null&&(r.match(/msie 8/i)||!B&&!b.useHighPerformance)&&navigator.platform.match(/win32|win64/i))b.specialWmodeCase=true,m("spcWmode"),b.wmode=null;i={name:c,id:c,src:a,width:"auto",height:"auto",quality:"high",allowScriptAccess:b.allowScriptAccess,bgcolor:b.bgColor,pluginspage:Sa+"www.macromedia.com/go/getflashplayer",title:"JS/Flash audio component (SoundManager 2)",type:"application/x-shockwave-flash",
wmode:b.wmode,hasPriority:"true"};if(b.debugFlash)i.FlashVars="debug=1";b.wmode||delete i.wmode;if(B)d=g.createElement("div"),l=['<object id="'+c+'" data="'+a+'" type="'+i.type+'" title="'+i.title+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="'+Sa+'download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" width="'+i.width+'" height="'+i.height+'">',f("movie",a),f("AllowScriptAccess",b.allowScriptAccess),f("quality",i.quality),b.wmode?f("wmode",b.wmode):"",
f("bgcolor",b.bgColor),f("hasPriority","true"),b.debugFlash?f("FlashVars",i.FlashVars):"","</object>"].join("");else for(h in d=g.createElement("embed"),i)i.hasOwnProperty(h)&&d.setAttribute(h,i[h]);pa();j=I();if(i=Z())if(b.oMC=v(b.movieID)||g.createElement("div"),b.oMC.id){n=b.oMC.className;b.oMC.className=(n?n+" ":b.swfCSS.swfDefault)+(j?" "+j:"");b.oMC.appendChild(d);if(B)h=b.oMC.appendChild(g.createElement("div")),h.className=b.swfCSS.swfBox,h.innerHTML=l;N=true}else{b.oMC.id=b.movieID;b.oMC.className=
b.swfCSS.swfDefault+" "+j;h=j=null;if(!b.useFlashBlock)if(b.useHighPerformance)j={position:"fixed",width:"8px",height:"8px",bottom:"0px",left:"0px",overflow:"hidden"};else if(j={position:"absolute",width:"6px",height:"6px",top:"-9999px",left:"-9999px"},o)j.left=Math.abs(parseInt(j.left,10))+"px";if($a)b.oMC.style.zIndex=1E4;if(!b.debugFlash)for(n in j)j.hasOwnProperty(n)&&(b.oMC.style[n]=j[n]);try{B||b.oMC.appendChild(d);i.appendChild(b.oMC);if(B)h=b.oMC.appendChild(g.createElement("div")),h.className=
b.swfCSS.swfBox,h.innerHTML=l;N=true}catch(q){throw Error(p("domError")+" \n"+q.toString());}}M=true;e();b._wD("soundManager::createMovie(): Trying to load "+a+(!K&&b.altURL?" (alternate URL)":""),1);return true};Y=function(){if(b.html5Only)return $(),false;if(b.o)return false;b.o=b.getMovie(b.id);if(!b.o)P?(B?b.oMC.innerHTML=qa:b.oMC.appendChild(P),P=null,M=true):$(b.id,b.url),b.o=b.getMovie(b.id);b.o&&m("waitEI");b.oninitmovie instanceof Function&&setTimeout(b.oninitmovie,1);return true};W=function(){setTimeout(Da,
1E3)};Da=function(){if(da)return false;da=true;q.remove(k,"load",W);if(J&&!Aa)return m("waitFocus"),false;var c;o||(c=b.getMoviePercent(),b._wD(p("waitImpatient",c===100?" (SWF loaded)":c>0?" (SWF "+c+"% loaded)":"")));setTimeout(function(){c=b.getMoviePercent();o||(b._wD("soundManager: No Flash response within expected time.\nLikely causes: "+(c===0?"Loading "+b.movieURL+" may have failed (and/or Flash "+h+"+ not present?), ":"")+"Flash blocked or JS-Flash security error."+(b.debugFlash?" "+p("checkSWF"):
""),2),!K&&c&&(m("localFail",2),b.debugFlash||m("tryDebug",2)),c===0&&b._wD(p("swf404",b.url)),t("flashtojs",false,": Timed out"+K?" (Check flash security or flash blockers)":" (No plugin/missing SWF?)"));!o&&Qa&&(c===null?b.useFlashBlock||b.flashLoadTimeout===0?(b.useFlashBlock&&ra(),m("waitForever")):aa(true):b.flashLoadTimeout===0?m("waitForever"):aa(true))},b.flashLoadTimeout)};C=function(){function c(){q.remove(k,"focus",C);q.remove(k,"load",C)}if(Aa||!J)return c(),true;Aa=Qa=true;b._wD("soundManager::handleFocus()");
T&&J&&q.remove(k,"mousemove",C);da=false;c();return true};Pa=function(){var c,a=[];if(b.useHTML5Audio&&b.hasHTML5){for(c in b.audioFormats)b.audioFormats.hasOwnProperty(c)&&a.push(c+": "+b.html5[c]+(!b.html5[c]&&u&&b.flash[c]?" (using flash)":b.preferFlash&&b.flash[c]&&u?" (preferring flash)":!b.html5[c]?" ("+(b.audioFormats[c].required?"required, ":"")+"and no flash support)":""));b._wD("-- SoundManager 2: HTML5 support tests ("+b.html5Test+"): "+a.join(", ")+" --",1)}};O=function(c){if(o)return false;
if(b.html5Only)return b._wD("-- SoundManager 2: loaded --"),o=true,F(),t("onload",true),true;var a;if(!b.useFlashBlock||!b.flashLoadTimeout||b.getMoviePercent())o=true,w&&(a={type:!u&&x?"NO_FLASH":"INIT_TIMEOUT"});b._wD("-- SoundManager 2 "+(w?"failed to load":"loaded")+" ("+(w?"security/load error":"OK")+") --",1);if(w||c){if(b.useFlashBlock&&b.oMC)b.oMC.className=I()+" "+(b.getMoviePercent()===null?b.swfCSS.swfTimedout:b.swfCSS.swfError);E({type:"ontimeout",error:a});t("onload",false);H(a);return false}else t("onload",
true);if(b.waitForWindowLoad&&!la)return m("waitOnload"),q.add(k,"load",F),false;else b.waitForWindowLoad&&la&&m("docLoaded"),F();return true};V=function(){m("init");if(o)return m("didInit"),false;if(b.html5Only){if(!o)q.remove(k,"load",b.beginDelayedInit),b.enabled=true,O();return true}Y();try{m("flashJS"),b.o._externalInterfaceTest(false),Ea(true,b.flashPollingInterval||(b.useHighPerformance?10:50)),b.debugMode||b.o._disableDebug(),b.enabled=true,t("jstoflash",true),b.html5Only||q.add(k,"unload",
ja)}catch(c){return b._wD("js/flash exception: "+c.toString()),t("jstoflash",false),H({type:"JS_TO_FLASH_EXCEPTION",fatal:true}),aa(true),O(),false}O();q.remove(k,"load",b.beginDelayedInit);return true};G=function(){if(oa)return false;oa=true;pa();var c=L.toLowerCase(),a=null,a=null,e=typeof console!=="undefined"&&typeof console.log!=="undefined";if(c.indexOf("sm2-usehtml5audio=")!==-1)a=c.charAt(c.indexOf("sm2-usehtml5audio=")+18)==="1",e&&console.log((a?"Enabling ":"Disabling ")+"useHTML5Audio via URL parameter"),
b.useHTML5Audio=a;if(c.indexOf("sm2-preferflash=")!==-1)a=c.charAt(c.indexOf("sm2-preferflash=")+16)==="1",e&&console.log((a?"Enabling ":"Disabling ")+"preferFlash via URL parameter"),b.preferFlash=a;if(!u&&b.hasHTML5)b._wD("SoundManager: No Flash detected"+(!b.useHTML5Audio?", enabling HTML5.":". Trying HTML5-only mode.")),b.useHTML5Audio=true,b.preferFlash=false;Ma();b.html5.usingFlash=La();x=b.html5.usingFlash;Pa();if(!u&&x)b._wD("SoundManager: Fatal error: Flash is needed to play some required formats, but is not available."),
b.flashLoadTimeout=1;g.removeEventListener&&g.removeEventListener("DOMContentLoaded",G,false);Y();return true};va=function(){g.readyState==="complete"&&(G(),g.detachEvent("onreadystatechange",va));return true};ga();q.add(k,"focus",C);q.add(k,"load",C);q.add(k,"load",W);T&&J&&q.add(k,"mousemove",C);g.addEventListener?g.addEventListener("DOMContentLoaded",G,false):g.attachEvent?g.attachEvent("onreadystatechange",va):(t("onload",false),H({type:"NO_DOM2_EVENTS",fatal:true}));g.readyState==="complete"&&
setTimeout(G,100)}var ha=null;if(typeof SM2_DEFER==="undefined"||!SM2_DEFER)ha=new U;D.SoundManager=U;D.soundManager=ha})(window);